### PR TITLE
cluster-autoscaler.spec: bump golang_version to 1.10.4

### PR DESCRIPTION
**Pull request by frobware**
Fixes: https://jira.coreos.com/browse/ART-242

### CODE REVIEW

**Comment by smarterclayton** [comment]
At this point we should probably drop spec files for components in favor of
multistage image builds.  I seeded these, but it’s just extra work for ART
and the team in the long run.


On Oct 25, 2018, at 11:19 AM, Andrew McDermott <notifications@github.com>
wrote:

/cc @smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/kubernetes-autoscaler/pull/7#issuecomment-433092844>,
or mute the thread

**Comment by frobware** [comment]
> At this point we should probably drop spec files for components in favor of multistage image builds.

Is there an example I can crib from?

**Comment by frobware** [comment]
This is blocking OCP builds - do we want to take this and follow up in favour of a multistage build?

**Comment by tbielawa** [comment]
"This is blocking OCP builds - do we want to take this and follow up in favour of a multistage build?"

We need to merge this PR so we can build full things again. Let's do that. 

As a follow up, lets get this into the multi-stage build club! Check on MoJo for DOC-1177281 if you need a starting point.

**Comment by smarterclayton** [comment]
I'm confused.  How does having a minimum bar that is too low cause the build to fail?  Why would 1.10.4 not satisfy >= 1.9.1?

**Comment by frobware** [comment]
> I'm confused. How does having a minimum bar that is too low cause the build to fail? Why would 1.10.4 not satisfy >= 1.9.1?

The merge of cluster-autoscaler-1.12 (#6) makes use of `strings.Builder()` which is only available in Go 1.10. This was noted in the Jira card but I may have confused things because I post-edited the commit description to reference that card having first put "/cc $YOU" as the description.

**Comment by frobware** [comment]
Still broken though: [ART-244 update](https://jira.coreos.com/browse/ART-244?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=52591#comment-52591)

**Pull request merged**
