### PR TITLE
Add upstream patch for --cloud-config option

### PR DESCRIPTION
**Pull request by elmiko**
This change brings in the upstream patch https://github.com/kubernetes/autoscaler/pull/3203

### CODE REVIEW

**Comment by elmiko** [comment]
opening this as draft because it needs the chain ending with #179 before it can merge, and there are 2 big commits that need to be merged.

**Comment by elmiko** [comment]
rebased

**Comment by elmiko** [comment]
this is ready for review, but still needs to wait for #179 
/hold

**Comment by elmiko** [comment]
this should go before #184

**Review by JoelSpeed — COMMENTED** [review]
/approve

The additional commit here is relatively straight forward, no issues from my side

**Comment by elmiko** [comment]
rebased after 179 merged
/hold cancel

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Pull request merged**
