### PR TITLE
Bug 1856127: Bump golang.org/x/text to v0.3.3

### PR DESCRIPTION
**Pull request by JoelSpeed**
Version v0.3.3 of the x/text package fixes a vulnerability in 
encoding/unicode that could lead to the UTF-16 decoder entering an 
infinite loop, causing the program to crash or run out of memory.

See https://groups.google.com/g/golang-announce/c/bXVeAmGOqz0?pli=1 for 
details.

Upstream contained in 
https://github.com/kubernetes/autoscaler/commit/bf955edc79bdb760018cf174a8aa67e523096c13

### CODE REVIEW

**Comment by enxebre** [comment]
Is there a PR to bump this upstream? otherwise we'll regress when rebasing.

**Comment by enxebre** [comment]
ignore me just saw you already linked it :)

**Comment by enxebre** [comment]
wouldn't we need to include the changes as in this PR to satisfy the new libs https://github.com/kubernetes/autoscaler/pull/3267/commits?
Let's hold this one for now and sync with @elmiko to see if we can proceed with the rebase and get this from the upstream.

**Comment by JoelSpeed** [comment]
I don't think we need any changes no. This PR is a very small subset of the upstream PR. To create this I recreated the temp directory for the vendor commit https://github.com/openshift/kubernetes-autoscaler/commit/3955223eeeeea11089cc15779fcf1b4c5d8b54e9, then updated just the single required dependency.
```
$ mkdir -p /tmp/ca-update-vendor.Hz3P/kubernetes
$ cd /tmp/ca-update-vendor.Hz3P/kubernetes
$ git init
$ git remote add origin git@github.com:kubernetes/kubernetes
$ git fetch --depth 1 origin f8ff8f44206ff4dd9b58386d96462b01a3d79fb1
$ git checkout FETCH_HEAD
$ cd $GOPATH/src/k8s.io/autoscaler/cluster-autoscaler
$ go get golang.org/x/text // Also update the replace statement in go.mod
$ go mod tidy && go mod vendor && go mod verify // equivalent of make vendor for most repos
```

The only changes in this PR are for the bump for `golang.org/x/text` `v0.3.2` to `v0.3.3` plus some files that were removed by me running `go mod vendor`, so I think the vendor dir was slightly out of date

**Comment by elmiko** [comment]
do we still need this now that the rebase has merge? (it looks like this package is at the proper version)

**Comment by JoelSpeed** [comment]
Yep, this was included in #164 and is no longer needed

**Pull request closed without merging**
