### PR TITLE
Implement cloudprovider/openshiftmachineapi using unstructured types and dynamic informers 

### PR DESCRIPTION
**Pull request by frobware**
Switch openshiftmachine cloudprovider implementation to use unstructured types and dynamic informers. This means we do not have to vendor the cluster-api repo and that will make ongoing vendoring easier as we continue to rebase against upstream cluster-autoscaler and upstream / downstream cluster-api.

To make the initial implementation easier I copied the Machine, MachineDeployment and MachineSet types locally. These need to be trimmed and now represent internal types. They are not supposed to be direct equivalents of those in the cluster-api project. I did this as a lot of the code referenced fields within these types.

With these changes the e2e-aws-operator CI tests pass as do the existing unit tests.

TODO:

- trim local Machine, MachineDeployment and MachineSet to the fields that are actually referenced

### CODE REVIEW

**Comment by frobware** [comment]
@enxebre @bison @elmiko I think this is now in good shape should again should you want to merge it and then build on top of it. It's perhaps the least intrusive diff and cleaning up the machine types, reducing the fields required can be done as discrete steps once (if) this merges.

**Comment by enxebre** [comment]
discussed with @frobware to follow up in https://github.com/openshift/kubernetes-autoscaler/pull/130 which handle deps with new approach

**Pull request closed without merging**
