### PR TITLE
Add rpm spec file and dockerfile for cluster autoscaler.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@sjenning @ingvagabund

### CODE REVIEW

**Comment by ingvagabund** [comment]
@aveshagarwal where does the spec file template live?

**Comment by ingvagabund** [comment]
@sjenning is this needed so the kubernetes-autoscaler can be build by the OpenShift builder?

**Comment by sjenning** [comment]
> @sjenning is this needed so the kubernetes-autoscaler can be built by the OpenShift builder?

Yes, it is part of the process for getting the CD team to do the RCM work for OCP.

**Comment by sjenning** [comment]
lets see if the bot integration is working
/lgtm

**Comment by sjenning** [comment]
> @aveshagarwal where does the spec file template live?

https://github.com/openshift/release/blob/master/tools/hack/golang/package.spec

**Comment by ingvagabund** [comment]
@sjenning awesome, thanks!!!

**Pull request merged**
