### PR TITLE
UPSTREAM: <carry>: openshiftmachineapi: remove unused fields

### PR DESCRIPTION
**Pull request by frobware**
Remove unused fields in types nodegroup and provider.

### CODE REVIEW

**Comment by enxebre** [comment]
/lgtm
can we run gofmt here to catch this things cc @paulfantom

**Comment by ingvagabund** [comment]
Code refactoring making the code a bit ligth-weighted. The more of these the better.

**Comment by frobware** [comment]
> can we run gofmt here to catch this things cc @paulfantom

This is not a gofmt issue. You need a specific linter to catch this.

**Comment by enxebre** [comment]
we'll want to run gofmt, golint and govet here, https://jira.coreos.com/browse/CLOUD-402

**Pull request merged**
