### PR TITLE
Bug 2103575: switched policy for PodDisruptionBudget from v1beta1 to v1 in time fo…

### PR DESCRIPTION
**Pull request by alexander-demichev**
…r 1.25

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by JoelSpeed** [comment]
The commit message needs updating here else it won't pass the checks

**Comment by elmiko** [comment]
tthis should be fixed in upstream at some point too, should we propose the change there as well?

**Comment by JoelSpeed** [comment]
This is a cherry-pick from the upstream already, just needs the commit message fixing up, or/ we should rebase onto the latest upstream

**Comment by elmiko** [comment]
> This is a cherry-pick from the upstream already, just needs the commit message fixing up, or/ we should rebase onto the latest upstream

ack, if we do a rebase on upstream things will get messy fast as the scale from zero stuff has merged there.

**Comment by alexander-demichev** [comment]
@elmiko should I close this PR? looks like we can fix it with the next rebase

**Comment by elmiko** [comment]
@alexander-demichev i guess it depends on what are next rebase is going to be. maybe we should discuss this on video chat?

**Comment by elmiko** [comment]
one more thought, i wonder if it makes sense to merge this now so that qe could start working on the validating the bug. otherwise they will have to wait until we finish the rebase.

**Comment by elmiko** [comment]
i am closing this issue as i am starting the rebase process for 1.25
/close

**Pull request closed without merging**
