### PR TITLE
Bug 2066270: UPSTREAM: <carry>: Fallback to CAPI annotations

### PR DESCRIPTION
**Pull request by enxebre**
This is to ensure the CAPI provider has the upstream CAPI annotations so it can be used with CAPI in hypershift.

cherry-picks https://github.com/openshift/kubernetes-autoscaler/pull/214
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
thanks Alberto!
/lgtm

**Comment by JoelSpeed** [comment]
/skip

To prevent endless retest-required from the bot

**Pull request merged**
