### PR TITLE
Bug 1948719: rebase on top of kubernetes/autoscaler 1.21

### PR DESCRIPTION
**Pull request by elmiko**
# 1.21 autoscaler rebase process

inspired by the commit description for the 1.20 rebase.
[pr #185](https://github.com/openshift/kubernetes-autoscaler/pull/185)

identify carry commits:
```
git log --oneline --no-merges b5f9b03f5689e88e13beceaff38b22d4d299a5b3..openshift/master
```
where `b5f9b0` reflects the changes since our last rebase (1.20.0). this is the
list of commits we will need to apply onto the new upstream version of the
autoscaler. ideally, some of these commits can be dropped.

After identifying the carry commits, the next step is to create the new commit-tree that
will be used for the rebase and then cherry pick the carry commits into the new branch.
The following commands cover these steps:

**Process**

```
$ git remote update # make sure we update our refs
$ git checkout 8dc1afb9a2fd188374620ee0d42358243e087655 # cluster-autoscaler-1.21
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge upstream/cluster-autoscaler-1.21' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit
$ git branch merge-1.21 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-1.21 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

With the `merge-1.21` branch in place, I cherry picked the carry commits which applied, resolved merge conflicts,
and finally tested the resulting tree against the unit test and end-to-end suite.

**Carried Commits**

These commits are for features which have not yet been accepted upstream, are integral to our CI platform, or are
specific to the releases we create for OpenShift.

```
fbe533c75 UPSTREAM: <carry>: openshift: Fix build with Go 1.16
bb49a8586 UPSTREAM: <carry>: Updating vertical-pod-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/e3b61ff1dde2bfc2bc7f2b5efdd155d1d3299cd7/images/vertical-pod-autoscaler.yml
c6f7a0a95 UPSTREAM: <carry>: VPA: Add Chen to approvers
b6e96d848 UPSTREAM: <carry>: VPA: Update Dockerfiles to use new registry
c99b47a92 UPSTREAM: <carry>: Updating vertical-pod-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/5a1293dd0f380abf50c12d65c36655486d7745d0/images/vertical-pod-autoscaler.yml
1a977f016 UPSTREAM: <carry>: Updating atomic-openshift-cluster-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/5a1293dd0f380abf50c12d65c36655486d7745d0/images/atomic-openshift-cluster-autoscaler.yml
1baf08f09 UPSTREAM: <carry>: openshift: add component and subcomponent to OWNERS
be51a45f9 UPSTREAM: <carry>: openshift: add fixes for unstructured scalable resources and node group discovery
024d0fa13 UPSTREAM: <carry>: Updating vertical-pod-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/f82a216a6a3707b80a635bace9367f1a8288b7a7/images/vertical-pod-autoscaler.yml
3bebbaec8 UPSTREAM: <carry>: Updating atomic-openshift-cluster-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/f82a216a6a3707b80a635bace9367f1a8288b7a7/images/atomic-openshift-cluster-autoscaler.yml
c20293a38 UPSTREAM: <carry>: openshift: Add tests for nodegroup TemplateNodeInfo
65b1b7d48 UPSTREAM: <carry>: openshift: Copy standard labels from an existing node if one exists
c0a685b68 UPSTREAM: <carry>: openshift: Ensure stable versions of generic labels are also included
8f67a8c4d UPSTREAM: <carry>: openshift: Updating vertical-pod-autoscaler/Dockerfile.rhel baseimages to match ocp-build-data config
1eba04782 UPSTREAM: <carry>: openshift: Updating images/cluster-autoscaler/Dockerfile.rhel baseimages to match ocp-build-data config
3bcdabda5 UPSTREAM: <carry>: openshift: Add vertical-pod-autoscaler/Dockerfile.rhel to match build configuration in ocp-build-data
24a45451c UPSTREAM: <carry>: openshift: Add images/cluster-autoscaler/Dockerfile.rhel to match build configuration in ocp-build-data
15a768ff9 UPSTREAM: <carry>: Convert the mem value consistently with other providers
bb9b3826b UPSTREAM: <carry>: openshift: Implement scale from zero
9bbf2eeb8 UPSTREAM: <carry>: openshift: Rename FailureMessage to ErrorMessage
f302c07bd UPSTREAM: <carry>: openshift: update cluster-autoscaler OWNERS
7f192ac8a UPSTREAM: <carry>: openshift: Revert "Adding config for event filtering"
aef98374e UPSTREAM: <carry>: openshift: Set default annotations, and cluster name label to use machine.openshift.io
e4c5171bd UPSTREAM: <carry>: Bump scripts go version to 1.13 and update path to cloudprovider/clusterapi
2839e4250 UPSTREAM: <carry>: openshift: Extend makefile with 'make goimports' target
589021834 UPSTREAM: <carry>: Fix git commit message verification script
d55f2e8f3 UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12
bb81822af UPSTREAM: <carry>: openshift: create git history verification script
1994c5ee3 UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile
7ad1cdce2 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: set golang_version to 1.10
5a6b51716 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: bump golang_version to 1.10.4
0ccae207e UPSTREAM: <carry>: openshift: Fix spec file to be consistent
56e629f74 UPSTREAM: <carry>: openshift: Bump embedded tools
0d6ceb9f0 UPSTREAM: <carry>: openshift: Fix the spec and hack scripts so the package can be built in both build systems
f66358622 UPSTREAM: <carry>: openshift: Add openshift/release Makefile and hack scripts
d5d0ca03c UPSTREAM: <carry>: openshift: Add dockerfile for cluster autoscaler.
356231f8c UPSTREAM: <carry>: openshift: Add spec file for cluster-autoscaler.
```

**Dropped Commits**

These commits were carried over the 1.20.x release history and represent work that has been accepted upstream or
is no longer needed in the openshift repository.

```
8667f0ca6 UPSTREAM: 3708: openshift: Bump github.com/heketi/heketi to v10.1.0
889eb8ac5 UPSTREAM: <carry>: openshift: remove Dockerfile.rhel7 files for vpa
9ca874bf8 UPSTREAM: <carry>: openshift: Update VPA builder images to use go 1.14
19f08493b UPSTREAM: <carry>: openshift: Add OpenShift VPA image builds
95b9ba5f9 UPSTREAM: <carry>: openshift: Add a RHEL7 dockerfile and standarize format
```

### CODE REVIEW

**Comment by elmiko** [comment]
think i missed a commit, should be a quick fix for tomorrow

**Comment by JoelSpeed** [comment]
Something has gone wrong in the vendor folder as we seem to have duplicationsof methods (I guess the files got renamed). Can we verify if the vendor is valid upstream and possibly reset ours to theirs? Not sure why it would differ though

**Comment by elmiko** [comment]
i have a feeling that although they created a branch for the 1.21 release, they haven't yet tagged that release. see https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.21/cluster-autoscaler/version/version.go

**Comment by elmiko** [comment]
updated
* include latest revendor from upstream
* remove some old carry commits for unused dockerfiles

**Comment by elmiko** [comment]
not quite sure what the issue is, i don't see the duplicates that go vet is reporting and the unit tests are passing locally.

**Comment by elmiko** [comment]
> Something has gone wrong in the vendor folder as we seem to have duplicationsof methods (I guess the files got renamed). Can we verify if the vendor is valid upstream and possibly reset ours to theirs? Not sure why it would differ though

after the latest rebase, i diff'd our vendor folder against the upstream cluster-autoscaler-release-1.21 branch vendor, and they are the same.

**Comment by elmiko** [comment]
i think the problem with go vet and unit tests is the older version(1.13) of go lang we use  in the test scripts. i tested locally with 1.16 and the same scripts passed.

i think we need this first, https://github.com/openshift/kubernetes-autoscaler/pull/202

**Comment by JoelSpeed** [comment]
The vet issues are because K/K has a problem with one of its interfaces in [this file](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/interface.go).

They have a `Framework` interface which embeds the `Handle` interface which embeds the `PluginsRunner` interface, this was changed about 2 months ago (Handle never used to embed `PluginsRunner`).

But the `PluginsRunner` interface duplicates methods from the `Framework` interface, causing `go vet` to fail.

Is there a way we can vet our code without having to vet the vendored dependencies?

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Pull request merged**
