### PR TITLE
Bug 1902289: Update gorilla websocket to v1.4.2

### PR DESCRIPTION
**Pull request by JoelSpeed**
I used the instructions [here](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.2/cluster-autoscaler/FAQ.md#how-can-i-update-ca-dependencies-particularly-k8siokubernetes) to manually update the dependencies to K8s v1.10.0 and then update the gorilla/websocket dependency to the latest version.

There were some issues along the way that I had to resolve:
- Caddy has moved from `github.com/mholt/caddy` to `github.com/caddyserver/caddy`, this had to be checked out manually
- Bitbucket dependencies would not checkout as part of godep restore, had to do this manually 
- `bitbucket.org/ww/goautoneg` seems to no longer exist, I have replaced it with the fork https://github.com/munnerz/goautoneg
- Some formatting issues were present after I updated the dependenices, if these are fixed in the upstream release branch, I have fixed them in the same way here too

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
this seems reasonable to me
/lgtm

**Review by elmiko — APPROVED** [review]

**Comment by JoelSpeed** [comment]
/approve

This should be merged now

**Pull request merged**
