### PR TITLE
[release-4.12] OCPBUGS-30911: Fix unstructured taint parsing in Cluster API provider

### PR DESCRIPTION
**Pull request by elmiko**
This is a manual cherry-pick of https://github.com/openshift/kubernetes-autoscaler/pull/289

### CODE REVIEW

**Comment by elmiko** [comment]
i needed to reform this PR since i can't push to the cherry-pick bot's copy. i'm not sure if we need to carry this nil check forward. we don't seem to be having the same trouble with newer versions of the e2e tests, but i think we need more investigation.

replaces #290

**Comment by elmiko** [comment]
i'm gonna fix up the commit history, just waiting for first e2e tests to finish

**Comment by elmiko** [comment]
i think we need to add this change to the more recent versions as well. as i am investigating the test failures, i can see that the scale from/to zero tests did not run on Joel's original PR. this fix needs to be tested against the scale from zero tests.

**Comment by elmiko** [comment]
i tested this manually locally and i can see that it is now properly processing the taint information.

```
I0326 16:01:14.376447 1023613 request.go:682] Waited for 1.049413921s due to client-side throttling, not priority and fairness, request: GET:https://api.ci-ln-dqc543k-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443/apis/tuned.openshift.io/v1?timeout=32s
Running Suite: Machine Suite
============================
Random Seed: 1711483268
Will run 1 of 37 specs

SSSSSSSSSSSSSSSSSS
------------------------------
[Feature:Machines] Autoscaler should use a ClusterAutoscaler that has 100 maximum total nodes count 
  It scales from/to zero
  /home/mike/dev/cluster-api-actuator-pkg/pkg/autoscaler/autoscaler.go:265
STEP: Creating ClusterAutoscaler
I0326 16:01:20.649375 1023613 autoscaler.go:186] Allocatable memory capacity of worker node "ip-10-0-152-100.us-west-2.compute.internal" is 14890524Ki
STEP: Starting Cluster Autoscaler event watcher
STEP: Creating a new MachineSet with 0 replicas
I0326 16:01:22.436683 1023613 autoscaler.go:273] Platform is AWS
STEP: Creating a MachineAutoscaler backed by MachineSet openshift-machine-api/ci-ln-dqc543k-76ef8-pwpf2jj694 - min:0, max:3
STEP: Creating scale-out workload e2e-autoscaler-workload-scale-from-zero: jobs: 3, memory: 1.0673528e+10
STEP: Waiting for machineSet replicas to scale out. Current replicas are 0, expected 3.
STEP: Waiting for machineSet replicas to scale out. Current replicas are 0, expected 3.
I0326 16:01:26.382424 1023613 autoscaler.go:239] cluster-autoscaler: cluster-autoscaler-default-f4b59c7c9-bwc6c became leader
STEP: Waiting for machineSet replicas to scale out. Current replicas are 0, expected 3.
STEP: Waiting for machineSet replicas to scale out. Current replicas are 0, expected 3.
STEP: Waiting for machineSet replicas to scale out. Current replicas are 0, expected 3.
I0326 16:01:37.518705 1023613 autoscaler.go:239] cluster-autoscaler-status: Scale-up: setting group MachineSet/openshift-machine-api/ci-ln-dqc543k-76ef8-pwpf2jj694 size to 3 instead of 0 (max: 3)
I0326 16:01:38.121650 1023613 autoscaler.go:239] cluster-autoscaler-status: Scale-up: group MachineSet/openshift-machine-api/ci-ln-dqc543k-76ef8-pwpf2jj694 size set to 3 instead of 0 (max: 3)
I0326 16:01:38.516442 1023613 autoscaler.go:239] e2e-autoscaler-workload-scale-from-zero-qhhwm: pod triggered scale-up: [{MachineSet/openshift-machine-api/ci-ln-dqc543k-76ef8-pwpf2jj694 0->3 (max: 3)}]
I0326 16:01:38.521768 1023613 autoscaler.go:239] e2e-autoscaler-workload-scale-from-zero-dwkv8: pod triggered scale-up: [{MachineSet/openshift-machine-api/ci-ln-dqc543k-76ef8-pwpf2jj694 0->3 (max: 3)}]
I0326 16:01:38.526675 1023613 autoscaler.go:239] e2e-autoscaler-workload-scale-from-zero-nnt9c: pod triggered scale-up: [{MachineSet/openshift-machine-api/ci-ln-dqc543k-76ef8-pwpf2jj694 0->3 (max: 3)}]
STEP: Waiting for machineSet replicas to scale out. Current replicas are 3, expected 3.
STEP: Waiting for the machineSet replicas to become nodes
```

**Review by damdo — COMMENTED** [review]
Thanks mike
/lgtm

**Comment by elmiko** [comment]
the azure and gcp failures are unrelated to this change

**Pull request merged**
