### PR TITLE
Merge upstream cluster-autoscaler-1.12

### PR DESCRIPTION
**Pull request by frobware**
This is a pre-requisite to landing the cluster-api cloud provider implementation for the cluster autoscaler.

### CODE REVIEW

**Comment by smarterclayton** [comment]
What’s up with the unit test,

**Comment by frobware** [comment]
> What’s up with the unit test,

Dunno:

```
$ go test -a -v k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce -run TestWaitForOp$
=== RUN   TestWaitForOp
--- PASS: TestWaitForOp (0.01s)
	autoscaling_gce_client_test.go:78: PASS:	handle(string)
	autoscaling_gce_client_test.go:78: PASS:	handle(string)
PASS
ok  	k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce	(cached)
```

```
$ go test -v k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce -run TestWaitForOp$
=== RUN   TestWaitForOp
--- PASS: TestWaitForOp (0.01s)
	autoscaling_gce_client_test.go:78: PASS:	handle(string)
	autoscaling_gce_client_test.go:78: PASS:	handle(string)
PASS
ok  	k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce	(cached)
```

```
$ go test -race -v k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce -run TestWaitForOp$
=== RUN   TestWaitForOp
--- PASS: TestWaitForOp (0.01s)
	mock.go:455: PASS:	handle(string)
	mock.go:455: PASS:	handle(string)
PASS
ok  	k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce	1.077s
````

Investigating.

**Comment by frobware** [comment]
OK, very possibly a timing issue; eventually reproduced by coping that binary to an AWS node and: 

```console
(dlv) funcs TestWaitForOp
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce.TestWaitForOp
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce.TestWaitForOpTimeout
(dlv) b k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce.TestWaitForOp
Breakpoint 1 set at 0x1f8692b for k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce.TestWaitForOp() /home/aim/go-projects/cloud245-update-openshift-autoscaler/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go:63
(dlv) c
> k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce.TestWaitForOp() /home/aim/go-projects/cloud245-update-openshift-autoscaler/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go:63 (hits goroutine(16):1 total:1) (PC: 0x1f8692b)
(dlv) n
> k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce.TestWaitForOp() /home/aim/go-projects/cloud245-update-openshift-autoscaler/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go:64 (PC: 0x1f86942)
(dlv) n
> k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce.TestWaitForOp() /home/aim/go-projects/cloud245-update-openshift-autoscaler/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go:65 (PC: 0x1f86950)
(dlv) c
--- FAIL: TestWaitForOp (5.95s)
    autoscaling_gce_client_test.go:77: 
            Error Trace:    autoscaling_gce_client_test.go:77
            Error:          Received unexpected error:
                            Timeout while waiting for operation operation-1505728466148-d16f5197 on  to complete.
            Test:           TestWaitForOp
    autoscaling_gce_client_test.go:78: FAIL:    handle(string)
                at: [autoscaling_gce_client_test.go:71]
    autoscaling_gce_client_test.go:78: FAIL:    handle(string)
                at: [autoscaling_gce_client_test.go:72]
    autoscaling_gce_client_test.go:78: FAIL: 0 out of 2 expectation(s) were met.
            The code you are testing needs to make 2 more call(s).
            at: [autoscaling_gce_client_test.go:78]
    autoscaling_gce_client_test.go:78: Expectations didn't match for Mock: *test.HttpServerMock
FAIL
Process 26217 has exited with status 1
```

**Comment by frobware** [comment]
@smarterclayton care to take another look?

**Comment by smarterclayton** [comment]
Do you plan to get that upstream?

**Comment by frobware** [comment]
> Do you plan to get that upstream?

https://github.com/kubernetes/autoscaler/pull/1356

**Pull request merged**
