### PR TITLE
Add openshift/release Makefile and hack scripts

### PR DESCRIPTION
**Pull request by ingvagabund**
Signed-off-by: Jan Chaloupka jchaloup@redhat.com

To align the tooling with https://github.com/openshift/release/tree/master/tools/hack/golang

Steps to use the scripts locally:
1. create symlink by running `./prep.sh` which just does:
    ```sh
    mkdir -p _output/local/go/src/k8s.io/
    ln -s $GOPATH/src/github.com/openshift/kubernetes-autoscaler _output/local/go/src/k8s.io/autoscaler
    ```
1. `export GOPATH=$(pwd)/_output/local/go`
1. make sure `imagebuilder` is under `$GOPATH/bin directory`

After that I am able to run:
* `make`
* `make build-rpms`
* `make build-images`

### CODE REVIEW

**Comment by ingvagabund** [comment]
@aveshagarwal can you verify both the spec and the Dockerfile file are still applicable in the CD infra? Could you also share steps how to verify that (either here or PM)?

Otherwise, the PR is ready for review and merging unless there are any blocking issues.

**Comment by ingvagabund** [comment]
Checking the spec file Clayton directed my to [1], I have updated the `cluster-autoscaler.spec` to be more aligned with [1].

[1] https://github.com/openshift/kubernetes-metrics-server/blob/master/metrics-server.spec#L118

**Comment by aveshagarwal** [comment]
@ingvagabund you can test using following steps:

1. Create a tar file from this repo that includes changes in this PR.
2. create a srpm: `rpmbuild -bs cluster-autoscaler.spec` .
3.  rpm -ivh <srpm>
4. rpmbuild -ba <path-to-spec-file>

Or you could directly:
1. Create a tar file from this repo that includes changes in this PR.
2. rpmbuild -ba <path-to-spec-file>. 

I had tested previously using tar file from here:https://github.com/openshift/kubernetes-autoscaler/archive/cluster-autoscaler-1.2.0.tar.gz

**Comment by ingvagabund** [comment]
@aveshagarwal the `rpmbuild -ba` is actually run by `make build-rpms`. Sorry, I meant the CD part. If there is a way to verify the CD team infrastructure can consume the spec file and the Dockerfile.

**Comment by aveshagarwal** [comment]
@ingvagabund yes I was talking about CD team part only. rpm and image building in rhel dist-git repo works on a source tar file and spec file, so as far as it works the same way, it will work for CD team too.

**Comment by aveshagarwal** [comment]
@ingvagabund another similar way is to checkout atomic-openshift-cluster-autoscaler dist-git repo and test your tar file and spec file there.

**Comment by ingvagabund** [comment]
@aveshagarwal the PR is good to go. The scratch build finishes successfully.

**Comment by aveshagarwal** [comment]
@ingvagabund it looks good to me. But it seems that cluster-autoscaler's Makefile is having issue during build due to following:

https://github.com/openshift/kubernetes-autoscaler/blob/master/cluster-autoscaler/Makefile#L9

Could you address this in your PR by not using the upstream Makefile and building cluster-autoscaler directly? Or does this PR already do this?

**Pull request merged**
