### PR TITLE
OCPCLOUD-1851: Upstream rebase to CA 1.26.1 and VPA 0.13

### PR DESCRIPTION
**Pull request by joelsmith**
This may be an intermediate rebase, depending upon whether more post-1.26.0 commits are expected prior to OpenShift 4.13.

After running this command:
```
rebasebot --source https://github.com/kubernetes/autoscaler:master --dest joelsmith/autoscaler:master --rebase joelsmith/autoscaler:rebase-bot-master --github-user-token <(yaml2json ~/.config/hub | jq -r '."github.com"[0].oauth_token') --dry-run
```
I also squashed 2 art bot commits which updated the base images for VPA.

### CODE REVIEW

**Comment by joelsmith** [comment]
This is a work in progress
/hold

/verify-owners

**Comment by elmiko** [comment]
/retitle OCPCLOUD-1851: Upstream rebase to CA 1.26.1 and VPA 0.13

**Comment by elmiko** [comment]
@joelsmith looking at the test results here and the commit history of what we moved upstream, i think we need to make sure we add a carry patch that reverts this chage https://github.com/kubernetes/autoscaler/commit/bb015b26a17ed1692d2a051e22adc6dfa09748e1

**Comment by enxebre** [comment]
Please let's make sure to honour non required `ci/prow/e2e-hypershift` to merge this PR

**Comment by elmiko** [comment]
added a commit to fix the label and taint support on openshift, i think that's all we need here.

**Comment by elmiko** [comment]
looks like we are seeing issues around slow node creation, i'm not entirely convinced that it is caused by this PR though.

/retest

**Comment by elmiko** [comment]
the aws, azure, and gcp tests failed due to some sort of must-gather error it looks like. i'm not sure about the hypershift failures, still seems like slow machine deletion perhaps (cc @enxebre might need your assistance understanding the failures).

/retest

**Comment by elmiko** [comment]
happy to see that e2-gcp-operator passed, still seeing some odd failures on the other tests.

/retest

**Comment by elmiko** [comment]
@enxebre it looks like the hypershift test has failed in a similar manner the last few runs, it appears like it waiting for machines to become nodes but i'm not sure of the exact failure. could you take a look and give some advice on if this is an autoscaler issue?

**Comment by elmiko** [comment]
@nee1esh the failing test is not required, i am curious to get a little more insight to the failure from someone who knows more about it.

/retest

**Comment by joelsmith** [comment]
We do expect the `git-history` test to fail since this is a rebase PR which includes upstream commits which we would not want labelled with the `UPSTREAM: ` prefix. So we will need to override that test here.

**Comment by elmiko** [comment]
@joelsmith correct, i was just waiting to see if we could get a comment on the failing hypershift tests. i'm not sure why it keeps failing.

**Comment by enxebre** [comment]
We need https://github.com/openshift/release/pull/36645 and retest afterwards.

**Comment by elmiko** [comment]
looks like we are good to go here

/approve
/lgtm

**Pull request merged**
