### PR TITLE
Bug 1992823: rebase on top of kubernetes/autoscaler 1.22

### PR DESCRIPTION
**Pull request by elmiko**
# 1.22 autoscaler rebase process

inspired by the commit description for the 1.21 rebase.
pr #201

identify carry commits. usually this step would involve looking through the history to determine the carry commits, but in this case i have squashed many of the carry commits as described in [OCPCLOUD-1207](https://issues.redhat.com/browse/OCPCLOUD-1207). the carried commits have been sourced from this branch https://github.com/elmiko/kubernetes-autoscaler/tree/openshift-1.21-history-cleanup

After identifying the carry commits, the next step is to create the new commit-tree that
will be used for the rebase and then cherry pick the carry commits into the new branch.
The following commands cover these steps:

**Process**

```
$ git remote update # make sure we update our refs
$ git checkout cluster-autoscaler-1.22.0
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge upstream/cluster-autoscaler-1.22' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit
$ git branch merge-1.22 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-1.22 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

With the `merge-1.22` branch in place, I cherry picked the carry commits from my history cleanup branch.

**Carried Commits**

These commits are for features which have not yet been accepted upstream, are integral to our CI platform, or are
specific to the releases we create for OpenShift.

```
f2519d93d UPSTREAM: <carry>: Implement scale from zero
8f4a01718 UPSTREAM: <carry>: Rename FailureMessage to ErrorMessage
1868d6a46 UPSTREAM: <carry>: Revert "Adding config for event filtering"
8bce568f3 UPSTREAM: <carry>: Set default annotations, and cluster name label to use machine.openshift.io
a5e56e715 UPSTREAM: <carry>: configure repository for OpenShift releases
```

**Dropped Commits**

These commits were present in the 1.21 branch, most of them have been squashed into the carried commits listed above.

```
fbe533c75 UPSTREAM: <carry>: openshift: Fix build with Go 1.16
bb49a8586 UPSTREAM: <carry>: Updating vertical-pod-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/e3b61ff1dde2bfc2bc7f2b5efdd155d1d3299cd7/images/vertical-pod-autoscaler.yml
c6f7a0a95 UPSTREAM: <carry>: VPA: Add Chen to approvers
b6e96d848 UPSTREAM: <carry>: VPA: Update Dockerfiles to use new registry
c99b47a92 UPSTREAM: <carry>: Updating vertical-pod-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/5a1293dd0f380abf50c12d65c36655486d7745d0/images/vertical-pod-autoscaler.yml
1a977f016 UPSTREAM: <carry>: Updating atomic-openshift-cluster-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/5a1293dd0f380abf50c12d65c36655486d7745d0/images/atomic-openshift-cluster-autoscaler.yml
1baf08f09 UPSTREAM: <carry>: openshift: add component and subcomponent to OWNERS
be51a45f9 UPSTREAM: <carry>: openshift: add fixes for unstructured scalable resources and node group discovery
024d0fa13 UPSTREAM: <carry>: Updating vertical-pod-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/f82a216a6a3707b80a635bace9367f1a8288b7a7/images/vertical-pod-autoscaler.yml
3bebbaec8 UPSTREAM: <carry>: Updating atomic-openshift-cluster-autoscaler builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/f82a216a6a3707b80a635bace9367f1a8288b7a7/images/atomic-openshift-cluster-autoscaler.yml
c20293a38 UPSTREAM: <carry>: openshift: Add tests for nodegroup TemplateNodeInfo
65b1b7d48 UPSTREAM: <carry>: openshift: Copy standard labels from an existing node if one exists
c0a685b68 UPSTREAM: <carry>: openshift: Ensure stable versions of generic labels are also included
8f67a8c4d UPSTREAM: <carry>: openshift: Updating vertical-pod-autoscaler/Dockerfile.rhel baseimages to match ocp-build-data config
1eba04782 UPSTREAM: <carry>: openshift: Updating images/cluster-autoscaler/Dockerfile.rhel baseimages to match ocp-build-data config
3bcdabda5 UPSTREAM: <carry>: openshift: Add vertical-pod-autoscaler/Dockerfile.rhel to match build configuration in ocp-build-data
24a45451c UPSTREAM: <carry>: openshift: Add images/cluster-autoscaler/Dockerfile.rhel to match build configuration in ocp-build-data
15a768ff9 UPSTREAM: <carry>: Convert the mem value consistently with other providers
bb9b3826b UPSTREAM: <carry>: openshift: Implement scale from zero
9bbf2eeb8 UPSTREAM: <carry>: openshift: Rename FailureMessage to ErrorMessage
f302c07bd UPSTREAM: <carry>: openshift: update cluster-autoscaler OWNERS
7f192ac8a UPSTREAM: <carry>: openshift: Revert "Adding config for event filtering"
aef98374e UPSTREAM: <carry>: openshift: Set default annotations, and cluster name label to use machine.openshift.io
e4c5171bd UPSTREAM: <carry>: Bump scripts go version to 1.13 and update path to cloudprovider/clusterapi
2839e4250 UPSTREAM: <carry>: openshift: Extend makefile with 'make goimports' target
589021834 UPSTREAM: <carry>: Fix git commit message verification script
d55f2e8f3 UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12
bb81822af UPSTREAM: <carry>: openshift: create git history verification script
1994c5ee3 UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile
7ad1cdce2 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: set golang_version to 1.10
5a6b51716 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: bump golang_version to 1.10.4
0ccae207e UPSTREAM: <carry>: openshift: Fix spec file to be consistent
56e629f74 UPSTREAM: <carry>: openshift: Bump embedded tools
0d6ceb9f0 UPSTREAM: <carry>: openshift: Fix the spec and hack scripts so the package can be built in both build systems
f66358622 UPSTREAM: <carry>: openshift: Add openshift/release Makefile and hack scripts
d5d0ca03c UPSTREAM: <carry>: openshift: Add dockerfile for cluster autoscaler.
356231f8c UPSTREAM: <carry>: openshift: Add spec file for cluster-autoscaler.
```

### CODE REVIEW

**Comment by elmiko** [comment]
it looks like the unit test is failing with a panic in the azure provider suite, all the capi tests pass.

**Comment by elmiko** [comment]
i have a feeling the unit test failures are related to the timeout we set in `hack/test-go.sh`. it is currently set to 120 seconds, but i see the azure test taking around 150-160 seconds. this test passes in the upstream, i am running some local tests with out timeout set to 180 seconds.

**Comment by elmiko** [comment]
confirmed my suspicions, i am updating the `hack/test-go.sh` script to have a 180 second time out.

**Comment by JoelSpeed** [comment]
/test e2e-azure-operator

Process looks good, tests seem to be passing for the most part
/approve

**Comment by Fedosin** [comment]
/lgtm
/hold

hold is for e2e-azure-operator to pass

**Comment by elmiko** [comment]
cancelling hold as all tests are passing

/hold cancel

**Pull request merged**
