### PR TITLE
Merge upstream/cluster-autoscaler-release 1.13

### PR DESCRIPTION
**Pull request by frobware**
The PR was created by first taking upstream/cluster-autoscaler-release-1.13 as the base then applying `UPSTREAM: <carry>` patches on top. The set of patches applied was taken from:

```console
$ git log --no-merges --format=oneline  upstream/cluster-autoscaler-release-1.13..openshift/master  
```

To create the merge commit I have used the following steps:

```console
$ git remote update
$ git checkout upstream/cluster-autoscaler-release-1.13
$ git checkout -b merge
$ git checkout openshift/master
$ echo 'merge upstream/cluster-autoscaler-release-1.13' | git commit-tree merge^{tree} -p HEAD -p merge
deadbeef12345678
$ git checkout deadbeef12345678
$ git cherry-pick ...all-the-things...
```

For details on the `merge^{tree}` syntax please read this [documentation](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects#_tree_objects).

The result of `git commit-tree` in this PR is https://github.com/openshift/kubernetes-autoscaler/pull/76/commits/810bb14c0a53261dfa3f2afb8e563ce84f8bd566

I then applied all the carry commits on top. There were additional changes required to the openshiftmachine cloud provider to make it build again. These changes are captured in the following commits: d4ecf32, 07edb0b and d175e89 and should be the focus of any review as all the other carry commits come from master.

This PR also revendors `openshift/cluster-api` based on https://github.com/openshift/cluster-api/pull/20.

As we have not been 100% consistent with the naming of our carry commits I have added the `UPSTREAM: <carry>: openshift` prefix to those commits that did not have this convention. This will make it easier to identify carry commits for the next rebase.

### CODE REVIEW

**Comment by frobware** [comment]
/hold 


TODO:
- Waiting on consensus on how we will handle upstream rebases.
- better PR description to explain how this PR was created

**Comment by frobware** [comment]
The picks are:

```sh
     1	a02da6ea3 UPSTREAM: <carry>: openshift: Add spec file for cluster-autoscaler.
     2	2c1e22e3b UPSTREAM: <carry>: openshift: Add dockerfile for cluster autoscaler.
     3	99c648c6b UPSTREAM: <carry>: openshift: Add openshift/release Makefile and hack scripts
     4	b905a5e03 UPSTREAM: <carry>: openshift: Fix the spec and hack scripts so the package can be built in both build systems
     5	c401a376c UPSTREAM: <carry>: openshift: Bump embedded tools
     6	a87e39008 UPSTREAM: <carry>: openshift: Fix spec file to be consistent
     7	e50c8dda2 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: bump golang_version to 1.10.4
     8	55a0b5926 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: set golang_version to 1.10
     9	f08d18969 UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api
    10	4c1805012 UPSTREAM: <carry>: openshift: initial cluster-api provider implementation
    11	53f645092 UPSTREAM: <carry>: openshift: Add a RHEL7 dockerfile and standarize format
    12	557c8ca0c UPSTREAM: <carry>: openshift: cluster-api switch to annotations
    13	208b6ad4b UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api/pkg/client/{listers,informers}_generated
    14	cbf1334a3 UPSTREAM: <carry>: openshift: Switch to informers for observing machines and machinesets
    15	5315425c2 UPSTREAM: <carry>: openshift: Move min/max constants to clusterapi_utils.go
    16	c8025043c UPSTREAM: <carry>: openshift: Additional logging in provider.NodeGroups()
    17	1aa27a3e5 UPSTREAM: <carry>: openshift: Rename clusterController to machineController
    18	b1ed8835d UPSTREAM: <carry>: openshift: Use NamespaceAll in lieu of ""
    19	38931763f UPSTREAM: <carry>: openshift: Rename field provider.clusterapi to clusterapiClient
    20	13a27d384 UPSTREAM: <carry>: openshift: gce: increase test timeout in TestWaitForGkeOp
    21	1ab3fb74c UPSTREAM: <carry>: openshift: Use 'machine' for machine parameter names
    22	4305bd665 UPSTREAM: <carry>: openshift: Decouple nodegroup via dependency injection
    23	d62fbdf34 UPSTREAM: <carry>: openshift: handle nil nodeGroup in calculateScaleDownGpusTotal
    24	5be6e0019 UPSTREAM: <carry>: openshift: Use node.Spec.ProviderID instead of node.Name
    25	b5f7c3b68 UPSTREAM: <carry>: openshift: fix calculation of max cluster size
    26	11670eda0 UPSTREAM: <carry>: openshift: utils: add unit tests for clusterapi_utils.go
    27	a7ada3cdb UPSTREAM: <carry>: openshift: Remove obsolete usage of "machine" annotation
    28	53b4cbb1f UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api/pkg/client/...fake packages
    29	617d26e59 UPSTREAM: <carry>: openshift: Add unit test for findMachine()
    30	7961bf0ac UPSTREAM: <carry>: openshift: Add unit test for findNodeByNodeName()
    31	3b8ed3394 UPSTREAM: <carry>: openshift: Add unit test for findMachineOwner()
    32	1efa1241c UPSTREAM: <carry>: openshift: Add unit test for findMachineByNodeProviderID()
    33	3d016fa40 UPSTREAM: <carry>: openshift: Add unit test for MachinesInMachineSet()
    34	d4f68d593 UPSTREAM: <carry>: openshift: Remove machineController.MachineSets() as it is not called
    35	205369fc9 UPSTREAM: <carry>: openshift: Rename ProviderConfig to ProviderSpec
    36	a011c6b95 UPSTREAM: <carry>: openshift: tests: copy autoscaler e2e test
    37	c8cf5ca18 UPSTREAM: <carry>: openshift: tests: add dependencies
    38	93ff484fc UPSTREAM: <carry>: openshift: assign ownership to cloud team
    39	8d6117b69 UPSTREAM: <carry>: openshift: cloudprovider: pivot to machine.openshift.io/v1beta1
    40	600c3ac05 UPSTREAM: <carry>: openshift: test/openshift/e2e: pivot to machine.openshift.io/v1beta1
    41	7e15119d8 UPSTREAM: <carry>: openshift: test/openshift/e2e: vendor github.com/openshift/cluster-api
    42	bdd7ec072 UPSTREAM: <carry>: openshift: test/openshift/e2e: fix formatting directive errors
    43	16d36a307 UPSTREAM: <carry>: openshift: test/openshift/e2e: correct APIVersion to machine.openshift.io/v1beta1
    44	2b0d545ee UPSTREAM: <carry>: openshift: test/openshift/e2e: really correct API version
    45	e66046bfe UPSTREAM: <carry>: openshift: Scope err variables in calls to PollImmediate
    46	7dafce209 UPSTREAM: <carry>: openshift: Rework test to also scale down
    47	dddeaceb7 UPSTREAM: <carry>: openshift: Cap MaxReplicas to 2
    48	b17278589 UPSTREAM: <carry>: openshift: test/openshift/e2e: switch namespace to openshift-machine-api
    49	f538a1d95 UPSTREAM: <carry>: openshift: Add newWorkLoad() helper function
    50	5ba3ee9e8 UPSTREAM: <carry>: openshift: Setup signal handler for test cleanup
    51	ab83bcebb UPSTREAM: <carry>: openshift: vendor: sigs.k8s.io/controller-runtime/pkg/runtime/signals
    52	ce56268e5 UPSTREAM: <carry>: openshift: Add MachineDeployment informers to controller
    53	7e2937c7c UPSTREAM: <carry>: openshift: Revert to whitebox testing
    54	d9e190dcc UPSTREAM: <carry>: openshift: Add interface ScalableResource
    55	43c0f3cb7 UPSTREAM: <carry>: openshift: MachineSet implementation of ScalableResource
    56	90fdea232 UPSTREAM: <carry>: openshift: MachineDeployment implementation of ScalableResource
    57	c634bd61d UPSTREAM: <carry>: openshift: add unit test for utils
    58	87a936f67 UPSTREAM: <carry>: openshift: add unit test for controller
    59	e9f6dc835 UPSTREAM: <carry>: openshift: add unit test for provider
    60	546c23828 UPSTREAM: <carry>: openshift: add unit test for nodegroup
    61	8a6faf28e UPSTREAM: <carry>: openshift: openshiftmachineapi: add feature gate for MachineDeployment support
    62	bffec3d91 UPSTREAM: <carry>: openshift: address review comments
    63	5ec3b3dc5 UPSTREAM: <carry>: openshift: log nodegroup discovery at level 4
    64	0cae6290b UPSTREAM: <carry>: openshift: test/openshift/e2e: bump dependencies
    65	0e8f8165c UPSTREAM: <carry>: openshift: validate node membership in DeleteNodes()
    66	24ee7643b UPSTREAM: <carry>: openshift: test/openshift/e2e: don't modify replica count
    67	27dd16c5d UPSTREAM: <carry>: openshift: create utility functions
    68	c8b888c00 UPSTREAM: <carry>: openshift: return no nodegroup when scaling bounds == 0
    69	77f2d24c7 UPSTREAM: <carry>: openshift: Remove old test functions
    70	38771cbdf UPSTREAM: <carry>: openshift: openshiftmachineapi: remove unused fields
    71	749053f39 UPSTREAM: <carry>: openshift: test/openshift: Revendor for cluster-api-actuator-pkg ginkgo suite
    72	9ee7fc37a UPSTREAM: <carry>: openshift: test/openshift: Run e2e ginkgo suite
    73	91086778d UPSTREAM: <carry>: openshift: fix max cluster size calculation on scale up
    74	4ca8bbec8 UPSTREAM: <carry>: openshift: test/openshift/e2e: add Autoscaler focused target
    75	882cb66c0 UPSTREAM: <carry>: openshift: test/openshift: go get dep if it doesn't exist
    76	2699890ef UPSTREAM: <carry>: openshift: test/openshift/Makefile: add rule to bump deps
    77	e361169fa UPSTREAM: <carry>: openshift: bump cluster-api-actuator-pkg
    78	953f73f75 UPSTREAM: <carry>: openshift: remove TODO
    79	dfeb66bc6 UPSTREAM: <carry>: openshift: Rework TestNodeGroupNewNodeGroup
    80	3824e025e UPSTREAM: <carry>: openshift: Rework TestNodeGroupResize
    81	4bc69b951 UPSTREAM: <carry>: openshift: Rework TestNodeGroupDeleteNodes
    82	e4d63512b UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroups
    83	ad93b060a UPSTREAM: <carry>: openshift: Rework TestControllerFindMachineByID
    84	efe336500 UPSTREAM: <carry>: openshift: Rework utils test funcs
    85	93a623a1f UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroupForNodeLookup
    86	aec883ffa UPSTREAM: <carry>: openshift: remove t.Helper() in test helpers
    87	7644eef6d UPSTREAM: <carry>: openshift: remove unused makeMachineOwner()
    88	6660f5499 UPSTREAM: <carry>: openshift: force test namespace ToLower()
    89	b96ebc91b UPSTREAM: <carry>: openshift: add spec to clusterTestConfig
    90	18de495b9 UPSTREAM: <carry>: openshift: simplify TestProviderConstructorProperties
    91	6b2a39b70 UPSTREAM: <carry>: openshift: remove parallel tests
    92	2d59abf48 UPSTREAM: <carry>: openshift: move all test utility functions
    93	bc2d47c81 UPSTREAM: <carry>: openshift: check for explicit errors in resize tests
    94	3a1dbadf3 UPSTREAM: <carry>: openshift: create git history verification script
    95	d7b61d89b UPSTREAM: <carry>: openshift: add unit test TestNodeGroupIncreaseSize
    96	48f37db25 UPSTREAM: <carry>: openshift: add unit test TestNodeGroupDecreaseTargetSize
    97	d4ecf32eb UPSTREAM: <carry>: openshift: cloudprovider updates for 1.13
    98	07edb0b1b UPSTREAM: <carry>: openshift: cloudprovider builder updates for 1.13
    99	d175e89c2 UPSTREAM: <carry>: openshift: expose KubeConfigPath in CA options
   100	27f2947f0 UPSTREAM: <carry>: openshift: vendor openshift/cluster-api
```

**Comment by frobware** [comment]
I would say the commits which are different to openshift/master are:
- https://github.com/openshift/kubernetes-autoscaler/pull/76/commits/d4ecf32ebe6c1ab06bac45630098d7975bd81c66
- https://github.com/openshift/kubernetes-autoscaler/pull/76/commits/07edb0b1b0310dbd1907b9c7bb78d1172f3ef3d6
- https://github.com/openshift/kubernetes-autoscaler/pull/76/commits/d175e89c22c05d304937a4a3bf4193d429787245

**Comment by frobware** [comment]
> Old version had '"Failed to create %q cloud provider" in the logging string. Might be helpful in this file as well.

I don't see this (openshift/master) machineapi_provider.go but I do see it here:

```console
$ ag "Failed to create %q cloud provider" 
cloudprovider/builder/cloud_provider_builder.go
230:            glog.Fatalf("Failed to create %q cloud provider: %v", name, err)
```

And it is true that it no longer exists in upstream/cluster-autoscaler-release-1.13.

```console
aim@spicy:~/go-projects/autoscaler-merge/src/k8s.io/autoscaler
$ ag "Failed to create %q cloud provider"
```

As `cloud_provider_builder.go` is upstream code I'm inclined to leave it as is.

**Comment by frobware** [comment]
/hold

Waiting for feature freeze exception to be granted.

/cc @enxebre

**Comment by smarterclayton** [comment]
I will take a look at the commit history and see whether this matches what I get if I recreate it.  Want to make sure we end up with a documentable process

**Comment by frobware** [comment]
> I will take a look at the commit history and see whether this matches what I get if I recreate it. Want to make sure we end up with a documentable process

I will also try your approach too as I think it uses less plumbing compared to `git commit-tree`.

**Comment by smarterclayton** [comment]
Ok, so tried my steps with #78 and grabbed these.  Basically:

1. ran my steps using d54edf1 as the base instead of origin/master
2. after I was done, used `git cherry-pick a02da6e...d175e89` to get yours
3. had to resolve cluster-autoscaler.spec not existing, everything else applied

What's different between mine and yours: 3ffad39db12e874724ea1cf02e68185ef34d182f..d175e89

Looks like makefile, vendor dir, hack, a few others.  Were those things you explicitly had cherry-picks for?  If not, this highlighted that those should also be their own cherrypicked commits.

**Comment by frobware** [comment]
> Looks like makefile, vendor dir, hack, a few others. Were those things you explicitly had cherry-picks for? If not, this highlighted that those should also be their own cherrypicked commits.

I explicitly did not cherry-pick anything that was in `cluster-autoscaler/vendor` knowing full well that I was going to revendor to pick up latest https://github.com/openshift/cluster-api/pull/20. There were three new commits that I made to make things compile again for 1.13 (cloudprovider API changes): 
- d4ecf32
- 07edb0b
- d175e89

**Comment by frobware** [comment]
/hold cancel

Exception was granted as long as it merges by Friday 5th April.

**Comment by frobware** [comment]
```console
level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating infrastructure resources..."
level=info msg="Waiting up to 30m0s for the Kubernetes API at https://api.ci-op-fmdrx7ht-1227b.origin-ci-int-aws.dev.rhcloud.com:6443..."
level=fatal msg="waiting for Kubernetes API: context deadline exceeded"
```

/retest

**Pull request merged**
