### PR TITLE
UPSTREAM: <carry>: cluster-api: revendor sigs.k8s.io/cluster-api at v0.0.4

### PR DESCRIPTION
**Pull request by frobware**
Vendor sigs.k8s.io/cluster-api at v0.0.4 to pickup ProviderConfig -> ProviderSpec field rename.

### CODE REVIEW

**Comment by frobware** [comment]
This is the preferred carry for the change introduced by PR #22

**Comment by frobware** [comment]
cc @ingvagabund @enxebre

**Comment by ingvagabund** [comment]
Hoping there will be another release soon. So we can include https://github.com/kubernetes-sigs/cluster-api/pull/663 as well. Otherwise

\lgtm

**Comment by ingvagabund** [comment]
> We can choose to redo this PR to pick up that change.

Let's merge this PR so the deps are properly updated. Once the new release is out, let's revendor.

**Comment by frobware** [comment]
> Let's merge this PR so the deps are properly updated. Once the new release is out, let's revendor.

/hold cancel

**Comment by frobware** [comment]
> \lgtm

Was that supposed to be forward slash?

**Comment by ingvagabund** [comment]
Yes :D

**Pull request merged**
