### PR TITLE
OCPCLOUD-2195: rebase on upstream 1.28.0 release

### PR DESCRIPTION
**Pull request by elmiko**
This commit rebases the autoscaler on top of the Kubernetes/Autoscaler 1.28.0 release. There are several commits that we carry on top of the upstream autoscaler and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(inspired by the commit description for the 1.18 rebase. [pr #139](https://github.com/openshift/kubernetes-autoscaler/pull/139))

**Process**

First we need to identify the carry commits that we currently have, this is done against our previous rebase to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits (run from the openshift/master branch)
```
git log -n 20 --oneline --no-merges
```
this is slightly different from previous rebases in that the history has gotten slightly wonky and i needed to manually inspect the carry patches.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:
```
$ git remote update # make sure we update our refs
$ git checkout cluster-autoscaler-1.28.0
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge upstream/cluster-autoscaler-1.28.0' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
deadbeef12345678 # id of new merge commit
$ git branch merge-1.28.0 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-1.28.0
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```

With the `merge-1.28.0` branch in place, I cherry picked the carry commits which applied, resolved merge conflicts, and finally tested the resulting tree against the unit test and end-to-end suite.

**Carried Commits**

These commits are for features which have not yet been accepted upstream, are integral to our CI platform, or are specific to the releases we create for OpenShift.
```
65cfc6208 UPSTREAM: 6066: Allow overriding the kubernetes.io/arch label set by the scale from zero methods via a new cmdline arg
061558ed7 UPSTREAM: <carry>: revert capacity annotations
ef2f569b8 UPSTREAM: <carry>: add machine api label and taint functionality
a3f3bfeee UPSTREAM: <carry>: Add vendor for balancer
b68ce96cf UPSTREAM: <carry>: update os::util::list_test_packages_under
b0bb5aeb0 UPSTREAM: <carry>: remove deprecated go test command
461f25adc UPSTREAM: <carry>: Have VPA ignore phantom containers named "POD"
d9b6825ce UPSTREAM: <carry>: Handle old Machine API specific machine delete annotation
14235e4ef UPSTREAM: <carry>: Rename FailureMessage to ErrorMessage
530db8027 UPSTREAM: <carry>: configure repository for OpenShift releases
```

**Dropped Commits**

These commits were squashed into the `530db8027` commit.
```
9fe29aaf4 (HEAD -> merge-1.28.0, origin/merge-1.28.0) UPSTREAM: <carry>: Sync OWNERS file
103eecdbe UPSTREAM: <carry>: Updating vertical-pod-autoscaler images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/da6a5af1fa96762cc8410f09fc28c0457280f59a/images/vertical-pod-autoscaler.yml
1f7bf8e71 UPSTREAM: <carry>: Use mod vendor for go test script
af3ff6883 UPSTREAM: <carry>: Updating atomic-openshift-cluster-autoscaler images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/ed337d94faaaa3782fcccf3a54d9a2256ba2aa9b/images/atomic-openshift-cluster-autoscaler.yml
967e9185b UPSTREAM: <carry>: update cluster-autoscaler dockerfile
```

But, of special note in this rebase is this commit
```
c74af5632 UPSTREAM: <carry>: revert capacity annotations
```
due to the scale from zero changes being accepted upstream we can now drop our carried patch. but, the upstream implementation has differed slightly from our's (mainly around annotation names). we will need to carry this patch until we can fix all the providers to properly use the new annotations.

Also of special note
```
808e1c9ba UPSTREAM: 6066: Allow overriding the kubernetes.io/arch label set by the scale from zero methods via a new cmdline arg
```
this commit is bringing in functionality for setting a default architecture on scale from zero through the command line. unfortunately, the upstream did not like our proposal and we have changed the way this works in the upstream. we will take the updated version when 1.29 release is created for the autoscaler. until then, @aleskandro is monitoring this and has a patch ready for our update in 1.29.

### CODE REVIEW

**Comment by elmiko** [comment]
@enxebre hypershift seems to be our only failure here, just curious for your opinion on the failure.

**Review by JoelSpeed — COMMENTED** [review]
Changes look fine once we work out what's wrong with hypershift, though given this is a manual rebase, perhaps we should squash down some of the boilerplate setup commits into a single commit, I think there are 5 that could be squashed into the first setup commit

**Comment by elmiko** [comment]
squashed some commits and updated the description

**Comment by JoelSpeed** [comment]
Changes look good to me, are we worried about the hypershift failure? Any confirmation from HyperShift if this is a known issue?
/test e2e-hypershift

**Comment by elmiko** [comment]
not sure if the hypershift test flaked, @enxebre had mentioned making some fixes to CI. will run again just in case.

/test e2e-hypershift

**Comment by elmiko** [comment]
looks like that did the trick, we just need labels and we are good to go.

@JoelSpeed ptal

**Pull request merged**
