### PR TITLE
OCPCLOUD-2733: rebase on upstream 1.31.0 release

### PR DESCRIPTION
**Pull request by elmiko**
This commit rebases the autoscaler on top of the Kubernetes/Autoscaler 1.31.0 release. There are several commits that we carry on top of the upstream autoscaler and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(inspired by the commit description for the 1.18 rebase. [pr #139](https://github.com/openshift/kubernetes-autoscaler/pull/139))

**Process**

First we need to identify the carry commits that we currently have, this is done against our previous rebase to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits (run from the openshift/master branch), these are the commits that begin with `UPSTREAM: ` up until the merge commit for the previous rebase commit (`merge upstream/cluster-autoscaler-1.30.1`)
```
git log -n 30 --oneline --no-merges
```

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:
```
$ git remote update # make sure we update our refs
$ git checkout cluster-autoscaler-1.31.0
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge upstream/cluster-autoscaler-1.31.0' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
deadbeef12345678 # id of new merge commit
$ git branch merge-1.31 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-1.31
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```

With the `merge-1.31` branch in place, I cherry picked the carry commits which applied, resolved merge conflicts, and finally tested the resulting tree against the unit test and end-to-end suite.

**Carried Commits**

These commits are for features which have not yet been accepted upstream, are integral to our CI platform, or are specific to the releases we create for OpenShift.
```
e4674574d UPSTREAM: <carry>: Fix unstructured taint parsing in Cluster API provider
1e019705a UPSTREAM: <carry>: revert capacity annotations
d76e8cbba UPSTREAM: <carry>: add machine api label and taint functionality
2adad66c5 UPSTREAM: <carry>: Have VPA ignore phantom containers named "POD"
7e6ff29ac UPSTREAM: <carry>: Handle old Machine API specific machine delete annotation
79d8030d3 UPSTREAM: <carry>: Rename FailureMessage to ErrorMessage
7e97b6851 UPSTREAM: <carry>: configure repository for OpenShift releases
```

**Squashed Commits**

These commits were squashed into the carried commits to help reduce the length of our history. All these commits have been squashed into their topically related commits.
```
10db73691 UPSTREAM: <carry>: Updating atomic-openshift-cluster-autoscaler-container image to be consistent with ART for 4.18 Reconciling with https://github.com/openshift/ocp-build-data/tree/1c7e6e27058c4590e342ecabe8bc96feeb68e7e5/images/atomic-openshift-cluster-autoscaler.yml
72c134510 UPSTREAM: <carry>: Updating ose-vertical-pod-autoscaler-container image to be consistent with ART for 4.17 Reconciling with https://github.com/openshift/ocp-build-data/tree/39d776b80aa929c42b98e8c50c25162b97b14e06/images/vertical-pod-autoscaler.yml
e23c8d462 UPSTREAM: <carry>: Update VPA ocp/builder images to openshift/release images
9017412fb UPSTREAM: <carry>: Sync OWNERS file
994400fcd UPSTREAM: <carry>: update os::util::list_test_packages_under
4d9aeca00 UPSTREAM: <carry>: remove deprecated go test command
```

**Dropped Commits**

These commits were dropped.
```
62a8e8c24 UPSTREAM: <drop>: Update vpa deployments to 1.1.2
7ee3a7a14 UPSTREAM: <drop>: Bump vpa to 1.1.2
b2d2b7d81 UPSTREAM: <drop>: add unit test for issue 6808
bc091b9c7 UPSTREAM: <drop>: Fix 6808
a0390f8c3 UPSTREAM: <drop>: Bump vpa version to 1.1.1
fdbf883fd UPSTREAM: <drop>: Bump VPA version to 1.1.1
```

Of special note in this rebase is this commit
```
1e019705a UPSTREAM: <carry>: revert capacity annotations
```
due to the scale from zero changes being accepted upstream we can now drop our carried patch. but, the upstream implementation has differed slightly from our's (mainly around annotation names). we will need to carry this patch until we can fix all the providers to properly use the new annotations. This patch can be dropped once the epic contained in https://issues.redhat.com/browse/OCPCLOUD-2136 is completed.

### CODE REVIEW

**Comment by elmiko** [comment]
added an upstream fix for the goimports, i have a feeling the deletion taint tests are still going to give us issues.

**Comment by elmiko** [comment]
i'll add a few more ignores to the snyk config

**Comment by JoelSpeed** [comment]
The security issues presented here may warrant a discussion with the VPA team, I can see some about unsanitised input, yet, I suspect the answer will be "we control the input so it's ok"

Otherwise changes here are looking good

Are the periodic issues known?

**Comment by elmiko** [comment]
cc @joelsmith , happy for your input on the security warnings

**Comment by elmiko** [comment]
> Are the periodic issues known?

yes, these are not new. they are related to the deletion taint issue we are working on.

**Comment by joelsmith** [comment]
I went to the Snyk dashboard and I have told Snyk to ignore the VPA issues as they were all false alarms.  There is still one in `tools/import-verifier/import-verifier.go` which I will leave for the Cloud team to ignore. I'll re-run the test to make sure that the VPA ones are properly ignored.

/test security

**Comment by elmiko** [comment]
@JoelSpeed looks like we are just down to the pathologically failing deletion taint tests

**Pull request merged**
