### PR TITLE
Bug 1843039: Add support for rescheduled pods with the same name in drain

### PR DESCRIPTION
**Pull request by jkaurredhat**
Bug fix for  : https://bugzilla.redhat.com/show_bug.cgi?id=1843039

Backport request from https://github.com/kubernetes/autoscaler/pull/830

### CODE REVIEW

**Comment by elmiko** [comment]
hi @jkaurredhat , thanks for the merge request. would you mind changing the title of this request to "Bug 1843039: $DESCRIPTION", replacing $DESCRIPTION with a small note about the change. this will help our CI automation pick up the github link and add it to the bugzilla.

**Comment by jkaurredhat** [comment]
@elmiko : thanks done the changes. Can you please check if it is now correct to give a green signal to automation. Let me know if any further changes are required.

**Comment by elmiko** [comment]
@jkaurredhat just wanted to keep you up to date, we are trying to figure out who needs to approve this to get it merged. sorry that it is taking longer than expected.

**Pull request merged**
