### PR TITLE
Rebase 1.19.0

### PR DESCRIPTION
**Pull request by elmiko**
This commit rebases the autoscaler on top of the Kubernetes/Autoscaler 1.19.0 release. There are several commits that we carry on top of the upstream autoscaler and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(inspired by the commit description for the 1.18 rebase. [pr #139](https://github.com/openshift/kubernetes-autoscaler/pull/139))

**Process**

First we need to identify the carry commits that we currently have, this is done against our previous rebase to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits:
```
git log --oneline --no-merges a1ddf4795100a7ac3a966ad2204ace7235c05ff1..openshift/master
```
where `a1ddf4` reflects the changes since our last rebase (1.18.0). this is the
list of commits we will need to apply onto the new upstream version of the
autoscaler. ideally, some of these commits can be dropped.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:
```
$ git remote update # make sure we update our refs
$ git checkout db76938c649a3717ca4fd8caf2944bf8ef340ecb # cluster-autoscaler-1.19.0
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge upstream/cluster-autoscaler-1.19.0' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
deadbeef12345678 # id of new merge commit
$ git branch merge-1.19.0 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-1.19.0
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```

With the `merge-1.19.0` branch in place, I cherry picked the carry commits which applied, resolved merge conflicts, and finally tested the resulting tree against the unit test and end-to-end suite.

**Carried Commits**

These commits are for features which have not yet been accepted upstream, are integral to our CI platform, or are specific to the releases we create for OpenShift.
```
4c60cef91 UPSTREAM: <carry>: openshift: Fallback to Status Replicas if Replicas nil when listing NodeGroups
feac275be UPSTREAM: <carry>: Convert the mem value consistently with other providers
487674be0 UPSTREAM: <carry>: openshift: Fallback to status if replicas nil in spec
fe618225e UPSTREAM: <carry>: openshift: Implement scale from zero
4feb7be3d UPSTREAM: <carry>: openshift: Rename FailureMessage to ErrorMessage
33715ff54 UPSTREAM: <carry>: openshift: update cluster-autoscaler OWNERS
a0492ee84 UPSTREAM: <carry>: openshift: Add OpenShift VPA image builds
55f8c76dc UPSTREAM: <carry>: openshift: Revert "Adding config for event filtering"
e5d75086b UPSTREAM: <carry>: openshift: Hardcode API group and annotations to machine.openshift.io
5db2eabe7 UPSTREAM: <carry>: Bump scripts go version to 1.13 and update path to cloudprovider/clusterapi
3dc78fcc6 UPSTREAM: <carry>: openshift: Extend makefile with 'make goimports' target
97681c560 UPSTREAM: <carry>: Fix git commit message verification script
561763adb UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12
8bee2fe79 UPSTREAM: <carry>: openshift: create git history verification script
b8c5d9d6b UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile
c55d13e35 UPSTREAM: <carry>: openshift: Add a RHEL7 dockerfile and standarize format
c81123283 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: set golang_version to 1.10
3bc1590b1 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: bump golang_version to 1.10.4
cdae7f285 UPSTREAM: <carry>: openshift: Fix spec file to be consistent
dacc7035f UPSTREAM: <carry>: openshift: Bump embedded tools
cef5e8a1d UPSTREAM: <carry>: openshift: Fix the spec and hack scripts so the package can be built in both build systems
320c648ce UPSTREAM: <carry>: openshift: Add openshift/release Makefile and hack scripts
4a7b05e02 UPSTREAM: <carry>: openshift: Add dockerfile for cluster autoscaler.
a34cf0a0d UPSTREAM: <carry>: openshift: Add spec file for cluster-autoscaler.
```

**Dropped Commits**

These commits were carried over the 1.18.x release history and represent work that has been accepted upstream.
```
e036217d8 UPSTREAM: <carry>: openshift: Support alias openshift-machine-api as cloud provider
90751c4b9 UPSTREAM: 3124: openshift: Allow small tolerance on memory capacity when comparing nodegroups
62834aa0a UPSTREAM: <carry>: remove redundant error checks in mark/unmark deletion functions
3ec206282 UPSTREAM: 3125: openshift: Rewrite DeleteNodesTwice test to check API not TargetSize
9e227899e UPSTREAM: <carry>: Add mutex to DeleteNodes
6f34947d3 UPSTREAM: <carry>: Get replicas always from API server
e7f689b4c UPSTREAM: <carry>: Compare against minSize in deleteNodes()
4903b8b15 UPSTREAM: 3034: openshift: Improve delete node mechanisms
e6900ffe1 UPSTREAM: 3057: openshift: Do not normalize Node IDs outside of CAPI provider
d2afb1111 UPSTREAM: 2983: openshift: Use FailureMessage instead of Phase to determine failed Machines
3f7cc57fe UPSTREAM: 2983: openshift: Add testing for fake provider IDs
028d97a2e UPSTREAM: 2983: openshift: Provide fake proivder IDs for failed machines
a6461e8bf UPSTREAM: <carry>: openshift: report MaxNodesTotal count
dfe75a4fd UPSTREAM: <carry>: openshift: Let the controller move on if machineDeployment resource does not exist.
```

### CODE REVIEW

**Comment by elmiko** [comment]
seems like the VPA build is breaking most of the tests, also the commit message for the upstream cluster autoscaler release seems to be breaking.

**Comment by elmiko** [comment]
i have a feeling the problem with the VPA is related to it requiring a different Go version.

**Comment by JoelSpeed** [comment]
I think you need to update the VPA base image from 1.12 to 1.13 which introduced the go `errors.Is`, it's 1.12 in the dockerfile https://github.com/elmiko/autoscaler/blob/60ccbcc43e6fcac860d518f26a7650348c6d2ede/vertical-pod-autoscaler/Dockerfile.openshift#L1 but also in the release config https://github.com/openshift/release/blob/6df7613c115132da2bfe3596ce23e7d305ef85c2/ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml#L29-L36, though I think the latter isn't actually doing anything so maybe we don't need to update that to get this to pass

**Comment by elmiko** [comment]
thanks for the suggestion Joel, i'm kinda wondering if should even be gating on building the VPA? (is there something i'm missing here)

**Comment by elmiko** [comment]
i think i see how i can go back and edit that carry commit to bump the image, then i can adjust the release repo. i'm curious if there are some openshift vpa folks i should inform/get involved?

also, about the git-history failure, that message is coming from upstream. do we need to change the linting script to allow it?

**Comment by enxebre** [comment]
@elmiko yeh @JoelSpeed is right. We need to include an extra commit to address https://github.com/openshift/kubernetes-autoscaler/pull/164#issuecomment-669845365 on top of https://github.com/openshift/kubernetes-autoscaler/pull/164/commits/55d6feefbbac93ca5ec4711e8e0d9626aa2dc34f cc @joelsmith 

For the next rebase I think we can conflate all this in one single commit, i.e "setup CI and automation":
```
5db2eabe7 UPSTREAM: <carry>: Bump scripts go version to 1.13 and update path to cloudprovider/clusterapi
3dc78fcc6 UPSTREAM: <carry>: openshift: Extend makefile with 'make goimports' target
97681c560 UPSTREAM: <carry>: Fix git commit message verification script
561763adb UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12
8bee2fe79 UPSTREAM: <carry>: openshift: create git history verification script
b8c5d9d6b UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile
c55d13e35 UPSTREAM: <carry>: openshift: Add a RHEL7 dockerfile and standarize format
c81123283 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: set golang_version to 1.10
3bc1590b1 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: bump golang_version to 1.10.4
cdae7f285 UPSTREAM: <carry>: openshift: Fix spec file to be consistent
dacc7035f UPSTREAM: <carry>: openshift: Bump embedded tools
cef5e8a1d UPSTREAM: <carry>: openshift: Fix the spec and hack scripts so the package can be built in both build systems
320c648ce UPSTREAM: <carry>: openshift: Add openshift/release Makefile and hack scripts
4a7b05e02 UPSTREAM: <carry>: openshift: Add dockerfile for cluster autoscaler.
a34cf0a0d UPSTREAM: <carry>: openshift: Add spec file for cluster-autoscaler.
```

This commit I think it can be dropped:
```
e036217d8 UPSTREAM: <carry>: openshift: Support alias openshift-machine-api as cloud provider
```

This we should contribute upstream and the drop them:
```
4c60cef91 UPSTREAM: <carry>: openshift: Fallback to Status Replicas if Replicas nil when listing NodeGroups
4feb7be3d UPSTREAM: <carry>: openshift: Rename FailureMessage to ErrorMessage
```

**Comment by elmiko** [comment]
seems like just updating the FROM directive for the VPA dockerfiles fixed the prow/images job.

**Comment by elmiko** [comment]
updated to remove this commit from the carries

```
e036217d8 UPSTREAM: <carry>: openshift: Support alias openshift-machine-api as cloud provider
```

**Comment by elmiko** [comment]
based on the info i've been reading[0], i have a feeling the `hack/verify_history.sh` script is always going to fail for a rebase type merge. it uses 2 environment variables to control the scope of the history to check, these are defined as `PULL_BASE_SHA` and `PULL_PULL_SHA` in Prow.

usually, these variable define a very narrow scope to check (eg 1 commit, or a couple in series). but this merge covers the entire history, so i have a feeling there is no way to make it pass. i _think_ we can safely ignore the history test for this PR.

[0] https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables

**Comment by enxebre** [comment]
```
Albertos-MacBook-Pro:autoscaler@albertogarla $ git log --oneline openshift/master..elmiko/openshift-rebase-1.19 --reverse
7111717ce Propagate scaling mode to containers. Correctly update ResourcePolicy and UpdatePolicy on update.
cfe5d7bc1 Fix misspelled parenthesis
19a78f698 Add some more documentation to clarify how labels and GPUs work with the ClusterAutoScaler on AWS
c53810cc0 Support arbitrary custom resource building template
.....
```

```
git log --oneline upstream/cluster-autoscaler-release-1.18..upstream/cluster-autoscaler-release-1.19 --no-merges --reverse
7111717ce Propagate scaling mode to containers. Correctly update ResourcePolicy and UpdatePolicy on update.
cfe5d7bc1 Fix misspelled parenthesis
19a78f698 Add some more documentation to clarify how labels and GPUs work with the ClusterAutoScaler on AWS
c53810cc0 Support arbitrary custom resource building template
....
```

Procedure seems ok to me.
/approve

**Comment by JoelSpeed** [comment]
/lgtm
/hold

@elmiko I assume you're happy for this to merge, but I'll hold until you're online just in case, unhold if you're ready

**Comment by elmiko** [comment]
@JoelSpeed i'm good to merge this, i don't think i would do any other adjustments for 1.19. for 1.20, we can target squashing all those commits Alberto mentioned.

**Comment by JoelSpeed** [comment]
/hold cancel
🥳

**Pull request merged**
