### PR TITLE
Bug 1875036: remove Dockerfile.rhel7 files for ca and vpa

### PR DESCRIPTION
**Pull request by elmiko**
This change removes the now deprecated Dockerfile.rhel7 files from the
cluster-autoscaler and the vertical-pod-autoscaler. These files are now
replaced by the Dockerfile.rhel file.

### CODE REVIEW

**Comment by elmiko** [comment]
i think we will need to wait until the changes in ocp-build-data have propogated before the tests will pass.

**Comment by enxebre** [comment]
Cross referencing https://github.com/openshift/ocp-build-data/pull/636
/approve

**Pull request merged**
