### PR TITLE
Rebase to upstream/cluster-autoscaler-release-1.14

### PR DESCRIPTION
**Pull request by frobware**
The PR was created by first taking upstream/cluster-autoscaler-release-1.14 as the base then applying UPSTREAM: <carry> patches on top. The set of picks applied was derived from:

`git log --oneline --no-merges 810bb14c0a53261dfa3f2afb8e563ce84f8bd566..openshift/master`

where 810bb14c0a53261dfa3f2afb8e563ce84f8bd566 reflects the changes since our last rebase (which was upstream/cluster-autoscaler-release-1.13).

And in that set of picks anything that was related to vendoring in `test/openshift` was dropped because we have moved to cloning the https://github.com/openshift/cluster-api-actuator-pkg when running the e2e tests. There is no value in picking all these historical commits as they were made redundant in PR #104 .

Equally, anything that was previously vendored in `cluster-autoscaler/vendor` has been dropped. We have to run the `cluster-autoscaler/fix_gopath.sh` script again to pick up the new kubernetes version (defined in `cluster-autoscaler/kubernetes.sync`) and as part of that process you have to `rm -rf vendor Godeps`.

To create the merge commit I have used the following steps:

```console
$ git remote update
$ git checkout upstream/cluster-autoscaler-release-1.14
$ git checkout -b merge
$ git checkout openshift/master
$ echo 'merge upstream/cluster-autoscaler-release-1.14' | git commit-tree merge^{tree} -p HEAD -p merge
deadbeef12345678
$ git checkout deadbeef12345678
$ git cherry-pick ...<all-the-things>...
```

Picks were as follows: 

```
PICKED/OK       a02da6ea3 UPSTREAM: <carry>: openshift: Add spec file for cluster-autoscaler.
PICKED/OK       2c1e22e3b UPSTREAM: <carry>: openshift: Add dockerfile for cluster autoscaler.
PICKED/CONFLICT 99c648c6b UPSTREAM: <carry>: openshift: Add openshift/release Makefile and hack scripts
PICKED/OK       b905a5e03 UPSTREAM: <carry>: openshift: Fix the spec and hack scripts so the package can be built in both build systems
PICKED/OK       c401a376c UPSTREAM: <carry>: openshift: Bump embedded tools
PICKED/OK       a87e39008 UPSTREAM: <carry>: openshift: Fix spec file to be consistent
PICKED/OK       e50c8dda2 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: bump golang_version to 1.10.4
PICKED/OK       55a0b5926 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: set golang_version to 1.10
DROP/VENDOR     f08d18969 UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api
PICKED/OK       4c1805012 UPSTREAM: <carry>: openshift: initial cluster-api provider implementation
PICKED/OK       53f645092 UPSTREAM: <carry>: openshift: Add a RHEL7 dockerfile and standarize format
PICKED/OK       557c8ca0c UPSTREAM: <carry>: openshift: cluster-api switch to annotations
DROP/VENDOR     208b6ad4b UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api/pkg/client/{listers,informers}_generated
PICKED/OK       cbf1334a3 UPSTREAM: <carry>: openshift: Switch to informers for observing machines and machinesets
PICKED/OK       5315425c2 UPSTREAM: <carry>: openshift: Move min/max constants to clusterapi_utils.go
PICKED/OK       c8025043c UPSTREAM: <carry>: openshift: Additional logging in provider.NodeGroups()
PICKED/OK       1aa27a3e5 UPSTREAM: <carry>: openshift: Rename clusterController to machineController
PICKED/OK       b1ed8835d UPSTREAM: <carry>: openshift: Use NamespaceAll in lieu of ""
PICKED/OK       38931763f UPSTREAM: <carry>: openshift: Rename field provider.clusterapi to clusterapiClient
DROP/UPSTREAM   13a27d384 UPSTREAM: <carry>: openshift: gce: increase test timeout in TestWaitForGkeOp
PICKED/OK       1ab3fb74c UPSTREAM: <carry>: openshift: Use 'machine' for machine parameter names
PICKED/OK       4305bd665 UPSTREAM: <carry>: openshift: Decouple nodegroup via dependency injection
DROP/UPSTREAM   d62fbdf34 UPSTREAM: <carry>: openshift: handle nil nodeGroup in calculateScaleDownGpusTotal
PICKED/OK       5be6e0019 UPSTREAM: <carry>: openshift: Use node.Spec.ProviderID instead of node.Name
DROP/UPSTREAM   b5f7c3b68 UPSTREAM: <carry>: openshift: fix calculation of max cluster size
PICKED/OK       11670eda0 UPSTREAM: <carry>: openshift: utils: add unit tests for clusterapi_utils.go
PICKED/OK       a7ada3cdb UPSTREAM: <carry>: openshift: Remove obsolete usage of "machine" annotation
DROP/VENDOR     53b4cbb1f UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api/pkg/client/...fake packages
PICKED/OK       617d26e59 UPSTREAM: <carry>: openshift: Add unit test for findMachine()
PICKED/OK       7961bf0ac UPSTREAM: <carry>: openshift: Add unit test for findNodeByNodeName()
PICKED/OK       3b8ed3394 UPSTREAM: <carry>: openshift: Add unit test for findMachineOwner()
PICKED/OK       1efa1241c UPSTREAM: <carry>: openshift: Add unit test for findMachineByNodeProviderID()
PICKED/OK       3d016fa40 UPSTREAM: <carry>: openshift: Add unit test for MachinesInMachineSet()
PICKED/OK       d4f68d593 UPSTREAM: <carry>: openshift: Remove machineController.MachineSets() as it is not called
DROP/VENDOR     205369fc9 UPSTREAM: <carry>: openshift: Rename ProviderConfig to ProviderSpec
PICKED/OK       a011c6b95 UPSTREAM: <carry>: openshift: tests: copy autoscaler e2e test
DROP/VENDOR     c8cf5ca18 UPSTREAM: <carry>: openshift: tests: add dependencies
PICKED/OK       93ff484fc UPSTREAM: <carry>: openshift: assign ownership to cloud team
PICKED/OK       8d6117b69 UPSTREAM: <carry>: openshift: cloudprovider: pivot to machine.openshift.io/v1beta1
DROP/VENDOR     600c3ac05 UPSTREAM: <carry>: openshift: test/openshift/e2e: pivot to machine.openshift.io/v1beta1
DROP/VENDOR     7e15119d8 UPSTREAM: <carry>: openshift: test/openshift/e2e: vendor github.com/openshift/cluster-api
DROP/VENDOR     bdd7ec072 UPSTREAM: <carry>: openshift: test/openshift/e2e: fix formatting directive errors
DROP/VENDOR     16d36a307 UPSTREAM: <carry>: openshift: test/openshift/e2e: correct APIVersion to machine.openshift.io/v1beta1
DROP/VENDOR     2b0d545ee UPSTREAM: <carry>: openshift: test/openshift/e2e: really correct API version
DROP/VENDOR     e66046bfe UPSTREAM: <carry>: openshift: Scope err variables in calls to PollImmediate
DROP/VENDOR     7dafce209 UPSTREAM: <carry>: openshift: Rework test to also scale down
DROP/VENDOR     dddeaceb7 UPSTREAM: <carry>: openshift: Cap MaxReplicas to 2
DROP/VENDOR     b17278589 UPSTREAM: <carry>: openshift: test/openshift/e2e: switch namespace to openshift-machine-api
DROP/VENDOR     f538a1d95 UPSTREAM: <carry>: openshift: Add newWorkLoad() helper function
DROP/VENDOR     5ba3ee9e8 UPSTREAM: <carry>: openshift: Setup signal handler for test cleanup
DROP/VENDOR     ab83bcebb UPSTREAM: <carry>: openshift: vendor: sigs.k8s.io/controller-runtime/pkg/runtime/signals
PICKED/OK       ce56268e5 UPSTREAM: <carry>: openshift: Add MachineDeployment informers to controller
PICKED/OK       7e2937c7c UPSTREAM: <carry>: openshift: Revert to whitebox testing
PICKED/OK       d9e190dcc UPSTREAM: <carry>: openshift: Add interface ScalableResource
PICKED/OK       43c0f3cb7 UPSTREAM: <carry>: openshift: MachineSet implementation of ScalableResource
PICKED/OK       90fdea232 UPSTREAM: <carry>: openshift: MachineDeployment implementation of ScalableResource
PICKED/OK       c634bd61d UPSTREAM: <carry>: openshift: add unit test for utils
PICKED/OK       87a936f67 UPSTREAM: <carry>: openshift: add unit test for controller
PICKED/OK       e9f6dc835 UPSTREAM: <carry>: openshift: add unit test for provider
PICKED/OK       546c23828 UPSTREAM: <carry>: openshift: add unit test for nodegroup
PICKED/OK       8a6faf28e UPSTREAM: <carry>: openshift: openshiftmachineapi: add feature gate for MachineDeployment support
PICKED/OK       bffec3d91 UPSTREAM: <carry>: openshift: address review comments
PICKED/OK       5ec3b3dc5 UPSTREAM: <carry>: openshift: log nodegroup discovery at level 4
DROP/VENDOR     0cae6290b UPSTREAM: <carry>: openshift: test/openshift/e2e: bump dependencies
PICKED/OK       0e8f8165c UPSTREAM: <carry>: openshift: validate node membership in DeleteNodes()
DROP/VENDOR     24ee7643b UPSTREAM: <carry>: openshift: test/openshift/e2e: don't modify replica count
PICKED/OK       27dd16c5d UPSTREAM: <carry>: openshift: create utility functions
PICKED/OK       c8b888c00 UPSTREAM: <carry>: openshift: return no nodegroup when scaling bounds == 0
PICKED/OK       77f2d24c7 UPSTREAM: <carry>: openshift: Remove old test functions
PICKED/OK       38771cbdf UPSTREAM: <carry>: openshift: openshiftmachineapi: remove unused fields
DROP/VENDOR     749053f39 UPSTREAM: <carry>: openshift: test/openshift: Revendor for cluster-api-actuator-pkg ginkgo suite
DROP/VENDOR     9ee7fc37a UPSTREAM: <carry>: openshift: test/openshift: Run e2e ginkgo suite
DROP/UPSTREAM   91086778d UPSTREAM: <carry>: openshift: fix max cluster size calculation on scale up
DROP/VENDOR     4ca8bbec8 UPSTREAM: <carry>: openshift: test/openshift/e2e: add Autoscaler focused target
DROP/VENDOR     882cb66c0 UPSTREAM: <carry>: openshift: test/openshift: go get dep if it doesn't exist
DROP/VENDOR     2699890ef UPSTREAM: <carry>: openshift: test/openshift/Makefile: add rule to bump deps
DROP/VENDOR     e361169fa UPSTREAM: <carry>: openshift: bump cluster-api-actuator-pkg
PICKED/OK       953f73f75 UPSTREAM: <carry>: openshift: remove TODO
PICKED/OK       dfeb66bc6 UPSTREAM: <carry>: openshift: Rework TestNodeGroupNewNodeGroup
PICKED/OK       3824e025e UPSTREAM: <carry>: openshift: Rework TestNodeGroupResize
PICKED/OK       4bc69b951 UPSTREAM: <carry>: openshift: Rework TestNodeGroupDeleteNodes
PICKED/OK       e4d63512b UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroups
PICKED/OK       ad93b060a UPSTREAM: <carry>: openshift: Rework TestControllerFindMachineByID
PICKED/OK       efe336500 UPSTREAM: <carry>: openshift: Rework utils test funcs
PICKED/OK       93a623a1f UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroupForNodeLookup
PICKED/OK       aec883ffa UPSTREAM: <carry>: openshift: remove t.Helper() in test helpers
PICKED/OK       7644eef6d UPSTREAM: <carry>: openshift: remove unused makeMachineOwner()
PICKED/OK       6660f5499 UPSTREAM: <carry>: openshift: force test namespace ToLower()
PICKED/OK       b96ebc91b UPSTREAM: <carry>: openshift: add spec to clusterTestConfig
PICKED/OK       18de495b9 UPSTREAM: <carry>: openshift: simplify TestProviderConstructorProperties
PICKED/OK       6b2a39b70 UPSTREAM: <carry>: openshift: remove parallel tests
PICKED/OK       2d59abf48 UPSTREAM: <carry>: openshift: move all test utility functions
PICKED/OK       bc2d47c81 UPSTREAM: <carry>: openshift: check for explicit errors in resize tests
PICKED/OK       3a1dbadf3 UPSTREAM: <carry>: openshift: create git history verification script
PICKED/OK       d7b61d89b UPSTREAM: <carry>: openshift: add unit test TestNodeGroupIncreaseSize
PICKED/OK       48f37db25 UPSTREAM: <carry>: openshift: add unit test TestNodeGroupDecreaseTargetSize
PICKED/OK       d4ecf32eb UPSTREAM: <carry>: openshift: cloudprovider updates for 1.13
PICKED/CONFLICT 07edb0b1b UPSTREAM: <carry>: openshift: cloudprovider builder updates for 1.13
PICKED/CONFLICT d175e89c2 UPSTREAM: <carry>: openshift: expose KubeConfigPath in CA options
DROP/VENDOR     95280c81e UPSTREAM: <carry>: openshift: vendor openshift/cluster-api
PICKED/OK       c72742506 UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile
PICKED/OK       43d15a922 UPSTREAM: <carry>: openshift: fix lint issue machineapi_provider
PICKED/OK       8a03c60d2 UPSTREAM: <carry>: openshift: simplify TestControllerFindMachineOwner
DROP/EMPTY      293ca33de UPSTREAM: <carry>: openshift: simplify TestControllerFindMachineByNodeProviderID
PICKED/OK       85dc7b88f UPSTREAM: <carry>: openshift: simplify TestControllerFindNodeByNodeName
PICKED/OK       92334c84b UPSTREAM: <carry>: openshift: simplify TestControllerMachinesInMachineSet
PICKED/OK       d3332b073 UPSTREAM: <carry>: openshift: remove TestControllerNodeGroupsSizes
PICKED/OK       50ea7e293 UPSTREAM: <carry>: openshift: simplify TestControllerNodeGroupForNodeWithMissingMachineOwner
PICKED/OK       23d04fac6 UPSTREAM: <carry>: openshift: simplify controller node lookup tests
PICKED/OK       f700b9b73 UPSTREAM: <carry>: openshift: expose nodegroup type for testing
PICKED/OK       adae8af33 UPSTREAM: <carry>: openshift: add new test helper
PICKED/OK       fa4cd7e1d UPSTREAM: <carry>: openshift: rework provider test setup
PICKED/OK       7bd999c69 UPSTREAM: <carry>: openshift: rework nodegroup test setup
PICKED/OK       65db39ce7 UPSTREAM: <carry>: openshift: rework controller test setup
PICKED/OK       4d0af4050 UPSTREAM: <carry>: openshift: move machineAnnotationKey constant
PICKED/OK       42607d7eb UPSTREAM: <carry>: openshift: add debugFormat const
PICKED/OK       1a6228b4a UPSTREAM: <carry>: openshift: shorten test helper names
DROP/VENDOR     89e384812 UPSTREAM: <carry>: openshift: bump test/openshift deps
PICKED/OK       80b7a7537 UPSTREAM: <carry>: openshift: disable MachineDeployment in normal operation
DROP/VENDOR     795ba2c4d UPSTREAM: <carry>: openshift: use type -p
DROP/VENDOR     2966cdf2c UPSTREAM: <carry>: openshift: vendor cluster-api-actuator-pkg
PICKED/OK       1a96ed4c0 UPSTREAM: <carry>: openshift: record max-nodes-total event
DROP/VENDOR     ab5326d37 UPSTREAM: <carry>: openshift: bump cluster-api-actuator-pkg
DROP/VENDOR     6fd78f66b UPSTREAM: <carry>: openshift: revendor cluster-api-actuator-pkg
PICKED/OK       ccb48d415 UPSTREAM: <carry>: openshift: simplify config creation
PICKED/OK       f15b3acce UPSTREAM: <carry>: openshift: add index to machine informer
PICKED/OK       5831b0533 UPSTREAM: <carry>: openshift: add findMachineByNodeProviderID
PICKED/OK       3bc3d12e2 UPSTREAM: <carry>: openshift: Prioritize machine search using provider ID
PICKED/OK       8894561b4 UPSTREAM: <carry>: openshift: add test to search using annotation
PICKED/OK       47af7842d UPSTREAM: <carry>: openshift: prioritize providerID in calls to Nodes()
PICKED/OK       2697932a1 UPSTREAM: <carry>: openshift: Add OpenShift VPA image builds
PICKED/OK       a707114c5 UPSTREAM: <carry>: openshift: Add joelsmith and sjenning to VPA OWNERS file
PICKED/OK       bf188e5cc UPSTREAM: <carry>: openshift: move maxnodes total event
PICKED/OK       c2f1516f4 UPSTREAM: <carry>: openshift: Revert "Merge pull request #90 from frobware/add-cluster-size-reached-event"
PICKED/OK       aa4c89f6c UPSTREAM: <carry>: openshift: move MaxNodesTotalReached event again
DROP/VENDOR     201abe72a UPSTREAM: <carry>: openshift: remove test/openshift/vendor
PICKED/OK       a8df8f9b1 UPSTREAM: <carry>: openshift: add test/openshift/hack scripts
DROP/VENDOR     35e7c7642 UPSTREAM: <carry>: openshift: update e2e test invocation
PICKED/OK       41f0c7a78 UPSTREAM: <carry>: openshift: update criteria for returning a nodegroup
PICKED/OK       01dbb612d UPSTREAM: <carry>: openshift: simplify test setup for nodes/replicas
```

For details on the merge^{tree} syntax please read this [documentation](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects#_tree_objects).

The result of git commit-tree in this PR is https://github.com/openshift/kubernetes-autoscaler/commit/b68c8ee26a8e4a2eccae1144b2a97a6c5f341868.

The previous rebase to upstream/cluster-autoscaler-release-1.13 was done in PR #76.

### CODE REVIEW

**Comment by frobware** [comment]
Picks applied:

```console
Key:

P/O  Picked OK
P/C  Picked but had conflicts
DROP now in 1.14

P/O  a02da6ea3 UPSTREAM: <carry>: openshift: Add spec file for cluster-autoscaler.
P/O  2c1e22e3b UPSTREAM: <carry>: openshift: Add dockerfile for cluster autoscaler.
P/C  99c648c6b UPSTREAM: <carry>: openshift: Add openshift/release Makefile and hack scripts
P/O  b905a5e03 UPSTREAM: <carry>: openshift: Fix the spec and hack scripts so the package can be built in both build systems
P/O  c401a376c UPSTREAM: <carry>: openshift: Bump embedded tools
P/O  a87e39008 UPSTREAM: <carry>: openshift: Fix spec file to be consistent
P/O  e50c8dda2 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: bump golang_version to 1.10.4
P/O  55a0b5926 UPSTREAM: <carry>: openshift: cluster-autoscaler.spec: set golang_version to 1.10
P/O  f08d18969 UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api
P/O  4c1805012 UPSTREAM: <carry>: openshift: initial cluster-api provider implementation
P/O  53f645092 UPSTREAM: <carry>: openshift: Add a RHEL7 dockerfile and standarize format
P/O  557c8ca0c UPSTREAM: <carry>: openshift: cluster-api switch to annotations
P/O  208b6ad4b UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api/pkg/client/{listers,informers}_generated
P/O  cbf1334a3 UPSTREAM: <carry>: openshift: Switch to informers for observing machines and machinesets
P/O  5315425c2 UPSTREAM: <carry>: openshift: Move min/max constants to clusterapi_utils.go
P/O  c8025043c UPSTREAM: <carry>: openshift: Additional logging in provider.NodeGroups()
P/O  1aa27a3e5 UPSTREAM: <carry>: openshift: Rename clusterController to machineController
P/O  b1ed8835d UPSTREAM: <carry>: openshift: Use NamespaceAll in lieu of ""
P/O  38931763f UPSTREAM: <carry>: openshift: Rename field provider.clusterapi to clusterapiClient
DROP 13a27d384 UPSTREAM: <carry>: openshift: gce: increase test timeout in TestWaitForGkeOp
P/O  1ab3fb74c UPSTREAM: <carry>: openshift: Use 'machine' for machine parameter names
P/O  4305bd665 UPSTREAM: <carry>: openshift: Decouple nodegroup via dependency injection
DROP d62fbdf34 UPSTREAM: <carry>: openshift: handle nil nodeGroup in calculateScaleDownGpusTotal
P/O  5be6e0019 UPSTREAM: <carry>: openshift: Use node.Spec.ProviderID instead of node.Name
DROP b5f7c3b68 UPSTREAM: <carry>: openshift: fix calculation of max cluster size
P/O  11670eda0 UPSTREAM: <carry>: openshift: utils: add unit tests for clusterapi_utils.go
P/O  a7ada3cdb UPSTREAM: <carry>: openshift: Remove obsolete usage of "machine" annotation
P/O  53b4cbb1f UPSTREAM: <carry>: openshift: vendor sigs.k8s.io/cluster-api/pkg/client/...fake packages
P/O  617d26e59 UPSTREAM: <carry>: openshift: Add unit test for findMachine()
P/O  7961bf0ac UPSTREAM: <carry>: openshift: Add unit test for findNodeByNodeName()
DROP 3b8ed3394 UPSTREAM: <carry>: openshift: Add unit test for findMachineOwner()
P/O  1efa1241c UPSTREAM: <carry>: openshift: Add unit test for findMachineByNodeProviderID()
P/O  3d016fa40 UPSTREAM: <carry>: openshift: Add unit test for MachinesInMachineSet()
P/O  d4f68d593 UPSTREAM: <carry>: openshift: Remove machineController.MachineSets() as it is not called
P/O  205369fc9 UPSTREAM: <carry>: openshift: Rename ProviderConfig to ProviderSpec
DROP a011c6b95 UPSTREAM: <carry>: openshift: tests: copy autoscaler e2e test
P/O  c8cf5ca18 UPSTREAM: <carry>: openshift: tests: add dependencies
P/O  93ff484fc UPSTREAM: <carry>: openshift: assign ownership to cloud team
P/O  8d6117b69 UPSTREAM: <carry>: openshift: cloudprovider: pivot to machine.openshift.io/v1beta1
P/O  600c3ac05 UPSTREAM: <carry>: openshift: test/openshift/e2e: pivot to machine.openshift.io/v1beta1
P/O  7e15119d8 UPSTREAM: <carry>: openshift: test/openshift/e2e: vendor github.com/openshift/cluster-api
P/O  bdd7ec072 UPSTREAM: <carry>: openshift: test/openshift/e2e: fix formatting directive errors
P/O  16d36a307 UPSTREAM: <carry>: openshift: test/openshift/e2e: correct APIVersion to machine.openshift.io/v1beta1
P/O  2b0d545ee UPSTREAM: <carry>: openshift: test/openshift/e2e: really correct API version
P/O  e66046bfe UPSTREAM: <carry>: openshift: Scope err variables in calls to PollImmediate
P/O  7dafce209 UPSTREAM: <carry>: openshift: Rework test to also scale down
P/O  dddeaceb7 UPSTREAM: <carry>: openshift: Cap MaxReplicas to 2
DROP b17278589 UPSTREAM: <carry>: openshift: test/openshift/e2e: switch namespace to openshift-machine-api
DROP f538a1d95 UPSTREAM: <carry>: openshift: Add newWorkLoad() helper function
P/O  5ba3ee9e8 UPSTREAM: <carry>: openshift: Setup signal handler for test cleanup
P/O  ab83bcebb UPSTREAM: <carry>: openshift: vendor: sigs.k8s.io/controller-runtime/pkg/runtime/signals
P/O  ce56268e5 UPSTREAM: <carry>: openshift: Add MachineDeployment informers to controller
P/O  7e2937c7c UPSTREAM: <carry>: openshift: Revert to whitebox testing
P/O  d9e190dcc UPSTREAM: <carry>: openshift: Add interface ScalableResource
P/O  43c0f3cb7 UPSTREAM: <carry>: openshift: MachineSet implementation of ScalableResource
P/O  90fdea232 UPSTREAM: <carry>: openshift: MachineDeployment implementation of ScalableResource
P/O  c634bd61d UPSTREAM: <carry>: openshift: add unit test for utils
P/O  87a936f67 UPSTREAM: <carry>: openshift: add unit test for controller
P/O  e9f6dc835 UPSTREAM: <carry>: openshift: add unit test for provider
P/O  546c23828 UPSTREAM: <carry>: openshift: add unit test for nodegroup
P/O  8a6faf28e UPSTREAM: <carry>: openshift: openshiftmachineapi: add feature gate for MachineDeployment support
P/O  bffec3d91 UPSTREAM: <carry>: openshift: address review comments
P/O  5ec3b3dc5 UPSTREAM: <carry>: openshift: log nodegroup discovery at level 4
P/O  0cae6290b UPSTREAM: <carry>: openshift: test/openshift/e2e: bump dependencies
P/O  0e8f8165c UPSTREAM: <carry>: openshift: validate node membership in DeleteNodes()
P/O  24ee7643b UPSTREAM: <carry>: openshift: test/openshift/e2e: don't modify replica count
P/O  27dd16c5d UPSTREAM: <carry>: openshift: create utility functions
P/O  c8b888c00 UPSTREAM: <carry>: openshift: return no nodegroup when scaling bounds == 0
P/O  77f2d24c7 UPSTREAM: <carry>: openshift: Remove old test functions
P/O  38771cbdf UPSTREAM: <carry>: openshift: openshiftmachineapi: remove unused fields
P/O  749053f39 UPSTREAM: <carry>: openshift: test/openshift: Revendor for cluster-api-actuator-pkg ginkgo suite
P/O  9ee7fc37a UPSTREAM: <carry>: openshift: test/openshift: Run e2e ginkgo suite
DROP 91086778d UPSTREAM: <carry>: openshift: fix max cluster size calculation on scale up
P/O  4ca8bbec8 UPSTREAM: <carry>: openshift: test/openshift/e2e: add Autoscaler focused target
P/O  882cb66c0 UPSTREAM: <carry>: openshift: test/openshift: go get dep if it doesn't exist
P/O  2699890ef UPSTREAM: <carry>: openshift: test/openshift/Makefile: add rule to bump deps
P/O  e361169fa UPSTREAM: <carry>: openshift: bump cluster-api-actuator-pkg
P/O  953f73f75 UPSTREAM: <carry>: openshift: remove TODO
P/O  dfeb66bc6 UPSTREAM: <carry>: openshift: Rework TestNodeGroupNewNodeGroup
P/O  3824e025e UPSTREAM: <carry>: openshift: Rework TestNodeGroupResize
P/O  4bc69b951 UPSTREAM: <carry>: openshift: Rework TestNodeGroupDeleteNodes
P/O  e4d63512b UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroups
P/O  ad93b060a UPSTREAM: <carry>: openshift: Rework TestControllerFindMachineByID
P/O  efe336500 UPSTREAM: <carry>: openshift: Rework utils test funcs
P/O  93a623a1f UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroupForNodeLookup
P/O  aec883ffa UPSTREAM: <carry>: openshift: remove t.Helper() in test helpers
P/O  7644eef6d UPSTREAM: <carry>: openshift: remove unused makeMachineOwner()
P/O  6660f5499 UPSTREAM: <carry>: openshift: force test namespace ToLower()
P/O  b96ebc91b UPSTREAM: <carry>: openshift: add spec to clusterTestConfig
P/O  18de495b9 UPSTREAM: <carry>: openshift: simplify TestProviderConstructorProperties
P/O  6b2a39b70 UPSTREAM: <carry>: openshift: remove parallel tests
P/O  2d59abf48 UPSTREAM: <carry>: openshift: move all test utility functions
P/O  bc2d47c81 UPSTREAM: <carry>: openshift: check for explicit errors in resize tests
P/O  3a1dbadf3 UPSTREAM: <carry>: openshift: create git history verification script
P/O  d7b61d89b UPSTREAM: <carry>: openshift: add unit test TestNodeGroupIncreaseSize
P/O  48f37db25 UPSTREAM: <carry>: openshift: add unit test TestNodeGroupDecreaseTargetSize
P/O  d4ecf32eb UPSTREAM: <carry>: openshift: cloudprovider updates for 1.13
P/C  07edb0b1b UPSTREAM: <carry>: openshift: cloudprovider builder updates for 1.13
P/C  d175e89c2 UPSTREAM: <carry>: openshift: expose KubeConfigPath in CA options
DROP 95280c81e UPSTREAM: <carry>: openshift: vendor openshift/cluster-api
P/O  c72742506 UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile
P/O  43d15a922 UPSTREAM: <carry>: openshift: fix lint issue machineapi_provider
P/O  8a03c60d2 UPSTREAM: <carry>: openshift: simplify TestControllerFindMachineOwner
P/O  293ca33de UPSTREAM: <carry>: openshift: simplify TestControllerFindMachineByNodeProviderID
P/O  85dc7b88f UPSTREAM: <carry>: openshift: simplify TestControllerFindNodeByNodeName
P/O  92334c84b UPSTREAM: <carry>: openshift: simplify TestControllerMachinesInMachineSet
P/O  d3332b073 UPSTREAM: <carry>: openshift: remove TestControllerNodeGroupsSizes
P/O  50ea7e293 UPSTREAM: <carry>: openshift: simplify TestControllerNodeGroupForNodeWithMissingMachineOwner
P/O  23d04fac6 UPSTREAM: <carry>: openshift: simplify controller node lookup tests
P/O  f700b9b73 UPSTREAM: <carry>: openshift: expose nodegroup type for testing
P/O  adae8af33 UPSTREAM: <carry>: openshift: add new test helper
P/O  fa4cd7e1d UPSTREAM: <carry>: openshift: rework provider test setup
P/O  7bd999c69 UPSTREAM: <carry>: openshift: rework nodegroup test setup
DROP 65db39ce7 UPSTREAM: <carry>: openshift: rework controller test setup
P/O  4d0af4050 UPSTREAM: <carry>: openshift: move machineAnnotationKey constant
P/O  42607d7eb UPSTREAM: <carry>: openshift: add debugFormat const
P/O  1a6228b4a UPSTREAM: <carry>: openshift: shorten test helper names
P/O  89e384812 UPSTREAM: <carry>: openshift: bump test/openshift deps
P/O  80b7a7537 UPSTREAM: <carry>: openshift: disable MachineDeployment in normal operation
P/O  795ba2c4d UPSTREAM: <carry>: openshift: use type -p
P/O  2966cdf2c UPSTREAM: <carry>: openshift: vendor cluster-api-actuator-pkg
P/O  1a96ed4c0 UPSTREAM: <carry>: openshift: record max-nodes-total event
P/O  ab5326d37 UPSTREAM: <carry>: openshift: bump cluster-api-actuator-pkg
P/O  6fd78f66b UPSTREAM: <carry>: openshift: revendor cluster-api-actuator-pkg
P/O  ccb48d415 UPSTREAM: <carry>: openshift: simplify config creation
P/O  f15b3acce UPSTREAM: <carry>: openshift: add index to machine informer
P/O  5831b0533 UPSTREAM: <carry>: openshift: add findMachineByNodeProviderID
P/O  3bc3d12e2 UPSTREAM: <carry>: openshift: Prioritize machine search using provider ID
P/O  8894561b4 UPSTREAM: <carry>: openshift: add test to search using annotation
P/O  47af7842d UPSTREAM: <carry>: openshift: prioritize providerID in calls to Nodes()
P/O  2697932a1 UPSTREAM: <carry>: openshift: Add OpenShift VPA image builds
P/O  a707114c5 UPSTREAM: <carry>: openshift: Add joelsmith and sjenning to VPA OWNERS file
P/O  bf188e5cc UPSTREAM: <carry>: openshift: move maxnodes total event
P/O  c2f1516f4 UPSTREAM: <carry>: openshift: Revert "Merge pull request #90 from frobware/add-cluster-size-reached-event"
P/O  aa4c89f6c UPSTREAM: <carry>: openshift: move MaxNodesTotalReached event again
P/O  201abe72a UPSTREAM: <carry>: openshift: remove test/openshift/vendor
P/O  a8df8f9b1 UPSTREAM: <carry>: openshift: add test/openshift/hack scripts
P/O  35e7c7642 UPSTREAM: <carry>: openshift: update e2e test invocation
P/O  41f0c7a78 UPSTREAM: <carry>: openshift: update criteria for returning a nodegroup
P/O  01dbb612d UPSTREAM: <carry>: openshift: simplify test setup for nodes/replicas
```

**Comment by frobware** [comment]
cc @joelsmith

**Comment by frobware** [comment]
cc @sjenning - a heads-up in case this affects the HPA builds.

**Comment by joelsmith** [comment]
:+1: Thanks! This is a big task and will really help us out on the VPA side.

**Comment by frobware** [comment]
The only difference between what we had previously for the cloudprovider is: 

```diff
$ git diff openshift/master ./cluster-autoscaler/cloudprovider/openshiftmachineapi/
diff --git a/cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go b/cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
index 383e527e5..84c1998de 100644
--- a/cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
+++ b/cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
@@ -24,7 +24,7 @@ import (
        machinev1beta1 "github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1"
        apiv1 "k8s.io/api/core/v1"
        "k8s.io/autoscaler/cluster-autoscaler/cloudprovider"
-       schedulercache "k8s.io/kubernetes/pkg/scheduler/cache"
+       schedulernodeinfo "k8s.io/kubernetes/pkg/scheduler/nodeinfo"
 )
 
 const (
@@ -188,7 +188,7 @@ func (ng *nodegroup) Nodes() ([]cloudprovider.Instance, error) {
 // allocatable information as well as all pods that are started on the
 // node by default, using manifest (most likely only kube-proxy).
 // Implementation optional.
-func (ng *nodegroup) TemplateNodeInfo() (*schedulercache.NodeInfo, error) {
+func (ng *nodegroup) TemplateNodeInfo() (*schedulernodeinfo.NodeInfo, error) {
        return nil, cloudprovider.ErrNotImplemented
 }
```

This represents a change made in upstream/cluster-autoscaler-release-1.14.

**Comment by frobware** [comment]
Key output from jenkins job: 

```console
I0620 10:48:53.232455       1 main.go:345] Cluster Autoscaler 1.14.3
```

**Comment by frobware** [comment]
/hold

Would like some feedback (if possible) from @joelsmith to ensure I haven't broken the VPA in any way.

**Comment by frobware** [comment]
Key output from CI/openshift:

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_kubernetes-autoscaler/107/pull-ci-openshift-kubernetes-autoscaler-master-e2e-aws-operator/306/artifacts/e2e-aws-operator/container-logs/test.log

```console
I0620 11:16:48.931790       1 main.go:345] Cluster Autoscaler 1.14.3
```

**Pull request merged**
