### PR TITLE
UPSTREAM: 4131: VPA: Added changes to support alternative recommender

### PR DESCRIPTION
**Pull request by wangchen615**
CherryPick the upstream PR 4131 to add changes to support alternative recommender

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
thanks Chen
/lgtm

**Comment by JoelSpeed** [comment]
/hold

As 1.23 is imminent, we will be rebasing this repository soon, which will bring in the upstream changes. I don't think we will need this but we can keep it open until the rebase is set up

**Comment by weinliu** [comment]
@JoelSpeed Hi Joel, I think we've got the 1.23 now. May I ask what the latest schedule for the rebasing is? the 4.10 code freeze date will be on 28th Jan. QE need some time for the testing after rebase.
Thanks!

**Comment by JoelSpeed** [comment]
@weinliu The rebase is coming in #218 which we are hoping to merge over the next couple of days, unfortunately there are a few test flakes which are making us nervous about the stability of the PR

**Comment by JoelSpeed** [comment]
This PR should no longer be required as we have completed the rebase which pulls in this change already
/close

**Pull request closed without merging**
