### PR TITLE
Bug 2087037: Rebase Autoscaler onto upstream release-1.24 branch

### PR DESCRIPTION
**Pull request by Fedosin**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/lgtm
/assign @elmiko 

@elmiko for final approval

**Comment by elmiko** [comment]
it looks good to me, i'd just like to see the aws-operator test pass

/retest-required

**Comment by elmiko** [comment]
i'm going to approve as it looks like the failures are not consistent, i'm guessing it's more due to flakes than something in this PR.

/approve

**Pull request merged**
